### ISSUE TITLE
`sncosmo.realize_lcs` should have a key to switch off scatter

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#105]
Currently, `sncosmo.realize_lcs()` obtains bandfluxes at times and filters indicated by obstable and calculates the fluxerror from the `skynoise` column of obstable, and the fluxes. It then adds a scatter to the flux values based on fluxerror. While all of this is correct, and should be the default, it is nice for checking to be able to turn the scatter off. Because it correctly uses the fluxes too to calculate the noise, this cannot be turned off by simply changing the `skynoise` column to 0.0. One could plot the model light curve, but it is nice to see what the points are at the observed times and bands only.

I would like to add a boolean argument scatter to the function's call signature with a default value of True. 
If scatter=True, the current behavior will be replicated. If scatter=False, then the scatter will not be added to the `model.bandflux` calls. This is implemented in  https://github.com/rbiswas4/sncosmo/tree/turnoffscatter

1. Is there a reason to avoid having this?
2. Can this be modified slightly to support similar use cases/ wishlist items other people have?

**Comment by kbarbary** [comment]
Sounds like a good idea to me. `scatter` does seem like a pretty good name for the argument. Can you create a PR from your branch?

**Comment by kbarbary** [comment]
closed by #106
