### ISSUE TITLE
The returns of mcmc_lc should store the ``chisq`` or ``lnlikelihood`` values corresponding to samples

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#107]
Unlike ``sncosmo.nestlc``, ``sncosmo.mcmc_lc`` does not store the chisq or log likelihood values values of the samples. While this can be easily done using the ``sncosmo.chisq`` function, this information must be getting calculated during the run, so it should be possible to keep this information and not have to recalculate it. And, I suppose,  it would be good to give it the same attribute name as in ``nest_lc``

`logl`: 1-d ndarray (length=nsamples); log(likelihood) for each sample.

**Comment by kbarbary** [comment]
There is a good reason for this, of course: the density of MCMC samples is proportional to the posterior, whereas in nested sampling, you need the value of the posterior at each sample to properly weight the samples.

**Comment by rbiswas4** [comment]
True, this makes it essential for logl be there for nest_lc, but there are applications to mcmc_lc where this is also useful like Importance sampling the results to a slightly different likelihood. Also, it would be useful to use this in calculating the returned parameter results differently.  

I would like to set up tests on how well importance sampling works for adding model covariance to the cases without model covariance.

**Comment by kbarbary** [comment]
I'd be OK with adding this, but we have to clear up the terminology. MCMC (specifically `emcee`) samples the posterior, so it's not the same as `logl` in nest_lc.

`logprob` might be a good name. `emcee` provides this as `flatlnprobability`.

**Comment by rbiswas4** [comment]
Ok maybe I am confused about terminology. But I am not looking for the posterior distribution. As you said, that is already there as the number density of samples. What I am looking for is the likelihood for each of the samples, or chisq for each of the samples (equivalent to likelihood if the likelihood is gaussian and the covariance constant), which were evaluated during the run and provided to the sampler.

**Comment by kbarbary** [comment]
The only thing provided to the `emcee` sampler is a function that calculates the posterior ([see the docs](http://dan.iel.fm/emcee/current/api/#the-affine-invariant-ensemble-sampler)), and so `emcee` only stores posterior samples.

**Comment by kbarbary** [comment]
You don't really need to know likelihoods to carry out importance sampling though. You just need to know the ratio of the prior to the fiducial prior at each sample. The nominal sample weights are one and the new sample weights are that ratio.

**Comment by rbiswas4** [comment]
Ok. We are definitely trying to use different terminology.

Let us try to forget about terminology for a minute and take a step back:

In the usual problem: 

We want to calculate $ P(\theta \vert data) $ where $\theta$ are a set of parameters for the light curve model like $\{t_0, x_0, x_1, c\}$ for the SALT model where the redshift is known, and data is the photometric data as expressed in sncosmo as a set of mjd, flux, fluxerror, (and let us keep model covariance out). To do this with an MCMC, we need to supply a prior function $P(\theta)$ and a function that calculates the chisq for each point $\theta$. For us this is the sncosmo.chisq function, that is evaluated. These evaluated  values for the samples are what I am looking for.

Using the likelihoods: Now, suppose someone said that the data is the same, the priors on the model parameters are the same, but the chisq function was (slightly) different (as would be the case due to a model covariance), and you have the samples from an MCMC run whose densities are the posteriors with the first chisq function. This can be done by reweighting the samples with ratios of the likelihood values. That is what I was calling importance sampling.

**Comment by kbarbary** [comment]
If the prior is the same, then the the ratio of likelihood values is the same as the ratio of posterior values, so just store the posterior values and reweight by new posterior values.

I think the terminology is pretty clear here: `posterior = likelihood * prior`. You can't store the likelihood values from emcee, because emcee never sees them; it only gets the product of `likelihood * prior`.

What's the point of using importance sampling to reweight by the likelihood values though? Usually people use importance sampling to reweight by the prior when the prior is cheap to calculate but the likelihood is expensive. If you are going to recalculate likelihood values, why not just run another MCMC?

**Comment by rbiswas4** [comment]
>  If the prior is the same, then the the ratio of likelihood values is the same as the ratio of posterior values, so just store the posterior values and reweight by new posterior values.

Yes, that would work for what I am thinking of... I guess you would be storing un-normalized posteriors and that is fine.

> I think the terminology is pretty clear here: posterior = likelihood * prior. 

Agree on the definition ... but I will defer agreement on terminology being clear :) . 

> You can't store the likelihood values from emcee, because emcee never sees them; it only gets the product of likelihood * prior.

Because it is calculated from two different functions the likelihood and prior (and by the way feeding the values as a product is not essential in an MCMC sampler in general, even though you need information from both the prior and the likelihood), you really have both the values before handing it off to emcee. Now, maybe emcee hands back the list of samples at the end but does not have a way of interacting and telling us that a sample has been accepted: That could make it technically difficult to do this.
  
Incidentally, if my prior is the posterior from a different experiment for which I have samples but not a numerical formula, how does this work? 

> What's the point of using importance sampling to reweight by the likelihood values though? Usually people use importance sampling to reweight by the prior when the prior is cheap to calculate but the likelihood is expensive. If you are going to recalculate likelihood values, why not just run another MCMC?

That is a good point. Obviously, it goes without saying that you certainly could, but then you go through burn-in, rejected samples, correlated samples etc, whereas you could do an MCMC, thin your samples and apply the weighting on the thinned samples to re-evaluate the posterior. On the flip side, you do have to worry about whether it is accurate enough, and so for a one time deal, it is probably not worth it. But if you are going to repeat similar exercises, and can convince yourself that it accurate enough(by testing on some cases if you are pedantic enough)  it could be a time saver.

**Comment by kbarbary** [comment]
Agreed. Seems like the action item here is to pass emcee's `flatlnprobability` to a `Result.logprob` attribute in the result from `mcmc_lc()`. 

> Incidentally, if my prior is the posterior from a different experiment for which I have samples but not a numerical formula, how does this work?

You'd have to approximate those samples with a continuous function.

**Comment by rbiswas4** [comment]
Yes, that sounds like the action item, but let us sit on it a bit. I plan to play a bit with emcee a bit to make sure that these quantities are what I think they are. 

> You'd have to approximate those samples with a continuous function.
I see.

**Comment by kbarbary** [comment]
Should we close this issue or do you still think `logprob` would be useful?

**Comment by rbiswas4** [comment]
I think we should close this issue for now. In the meantime I talked to @dfm about this, and he said he had a hack to get the likelihood values. So, I think it would be productive to implement his hack, but am kind of swamped at the moment.

**Comment by kbarbary** [comment]
I imagine the hack is something like

```
loglike = sampler.flatlnprobability - np.array(map(lnpriorfn, sampler.flatchain))
```

where `lnpriorfn` gives the log prior for a given point in parameter space.

Closing this for now. Feel free to reopen later.
