### ISSUE TITLE
supernova luminosity

### ISSUE THREAD

**Issue by AlexGKim** [sncosmo/sncosmo#118]
How do I create a model of a SALT2 source with known Bessel ab absolute magnitude in its rest frame, and how do I retrieve its luminosity?  Note that redshift and cosmology is unnecessary for any of these operations.

**Comment by dannygoldstein** [comment]
The `set_source_peakabsmag` function is not cosmology agnostic. There is a line in there that takes the model redshift, assumes a cosmology and computes a distance modulus to compute the apparent peak magnitude:

```python
m = absmag + cosmo.distmod(self._parameters[0]).value
```

**Comment by rbiswas4** [comment]
In the language that we have a model is what is observed, so cosmology and redshift are necessary. To define the source with Bessell ab absolute magnitude you do not need this information, but right now there is no way to set the absolute magnitude of a source directly without cosmology/redshift.
```
model = sncosmo.Model(source='SALT2')
model.set(z=0.5, c=0., x1=0.1)
from astropy.cosmology import Planck13 as cosmo
model.set_source_peakabsmag(-19.5, 'bessellB', 'ab', cosmo=cosmo)
```

**Comment by kbarbary** [comment]
This is actually quite doable without redshift or cosmology.

```python
source = sncosmo.get_source('salt2')
source.set_peakmag(-19.5, 'bessellb', 'ab')  # magnitude at 10pc
wave = np.linspace(source.minwave(), source.maxwave(), 1000)
flux = source.flux(0., wave)  # flux in erg/s/cm^2/A at phase=0 at 10pc

# now integrate flux over wavelength and sphere:
import astropy.units as u
sphere_area_cm2 = 4 * np.pi * (10. * u.pc.to(u.cm))**2
luminosity = np.sum(flux * np.gradient(wave)) * sphere_area_cm2   # result is 1.349e43 erg/s
```

**Comment by kbarbary** [comment]
Questions like this might be better suited to the mailing list than a github issue in the future: https://groups.google.com/forum/#!forum/sncosmo

Closing as resolved.
