### ISSUE TITLE
TypeError in latest sncosmo version

### ISSUE THREAD

**Issue by MichelleLochner** [sncosmo/sncosmo#127]
Has anyone else seen this error in the latest sncosmo version?

```TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('S32') dtype('S32') dtype('S32')```

It arises from fit_lc and must have something to do with the upgraded version of sncosmo, or (more likely) one of the packages it upgrades. 

I can confirm I haven't seen this in version 1.0, with astropy version 1.0.0, numpy 1.8.2 and scipy 0.13.3, but it does come up with sncosmo 1.1.1 and its upgraded dependencies.

I can post a minimal working example if you need but I'm hoping this is something someone's seen and knows how to fix.

Thanks!

**Comment by kbarbary** [comment]
Haven't seen that sort of error before. A minimal example would be good, or even just more of the traceback to start.

**Comment by MichelleLochner** [comment]
Ok it turns out not to be an sncosmo problem. It was to do with how I was collecting results from fit_lc, not from within fit_lc. Sorry to waste time!

**Comment by kbarbary** [comment]
No problem; good to know it's not an sncosmo bug!
