### ISSUE TITLE
Link to SFD98 map broken

### ISSUE THREAD

**Issue by ufeindt** [sncosmo/sncosmo#129]
The link to the SFD98 MW dust map in the "Adding Milky Way dust" example (http://sncosmo.readthedocs.org/en/latest/models.html#adding-milky-way-dust) is broken. Is there any mirror for it?

I found it on this page: http://lambda.gsfc.nasa.gov/product/foreground/f_products.cfm
but I'm not sure whether the file is the right one, e.g. it uses HEALPix with nside=512 while - guessing from the file name in the documentation - the expected file might be nside=4096.

**Comment by kbarbary** [comment]
I'm not aware of anyone actively hosting the maps anymore (and neither is David Schlegel himself!) So, I have the data mirrored. `wget http://sncosmo.github.io/data/dust/[file]` where file is any of

```
SFD_dust_4096_ngp.fits
SFD_mask_4096_ngp.fits
SFD_dust_4096_sgp.fits
SFD_mask_4096_sgp.fits
```

Could you submit a PR correcting the docs with this information?
