### ISSUE TITLE
Is the definition of the SALT2 model slightly different from the original paper?

### ISSUE THREAD

**Issue by MichelleLochner** [sncosmo/sncosmo#131]
I just wanted to check what definition of SALT2 is used in sncosmo because it seems slightly different from the original Guy et al. (2007) paper:
http://arxiv.org/pdf/astro-ph/0701828v1.pdf

The difference is in the definition of the colour correction term, which in the Guy paper is:
_exp(c CL(lambda))_

but in the sncosmo documentation is:
_CL(lambda)^c_

Is it just that you've used _ln(CL)_ in sncosmo but left it as _CL_ in the documentation?

I've used sncosmo for SALT2 fits so I want to make sure I get the definition right.

**Comment by rbiswas4** [comment]
It is the standard SALT definition. Maybe there is  typo in the documentation ...

**Comment by kbarbary** [comment]
Yes, I think the docs are wrong.

The relevant sections of code are [here](https://github.com/sncosmo/sncosmo/blob/b2f154004e62cc5928e2af8379ab9b206602d4fa/sncosmo/models.py#L660-L662) and [here](https://github.com/sncosmo/sncosmo/blob/b2f154004e62cc5928e2af8379ab9b206602d4fa/sncosmo/models.py#L902-L905). Turning those code lines into pseudo-code, the model flux is given by:
```
flux = x0 * (M0(t, lambda) + x1 * M1(t, lambda)) * clbase(lambda)**c
```
where `clbase` is
```
clbase(lambda) = 10. ** (-0.4 * CL(lambda))
```
where CL is the extinction in magnitudes for c=1. I think there is a constant factor difference between this definition and the one in the guy paper.

**Comment by pruzhinskaya** [comment]
Actually both `snfit` (Guy et al.) and `sncosmo` use the same formula, but the `snfit` documentation also needs to be clarified. 
The exact formula applied in snfit is

`exp(c * const * CL_snfit(lambda))`,

where `const = ln10/2.5`.

`CL_snfit(lambda) = -CL_sncosmo(lambda)`.

So, if we take into account this constant (I found it only in snfit code) there will be no any difference between the formula used in sncosmo and the one implemented in snfit.

**Comment by rbiswas4** [comment]
So, you are agreeing that these are the same , right? That constant is simply transforming from base 10 to base `e`

**Comment by pruzhinskaya** [comment]
Yes, exactly.

**Comment by kbarbary** [comment]
I clarified the sncosmo documentation a bit in c426a01. (It doesn't yet appear in the latest documentation build due to some bug occurring on readthedocs.)

Also, note that sncosmo's SALT2 implementation is now closely tested against snfit.
