### ISSUE TITLE
some csp bandpasses have negative transmissions

### ISSUE THREAD

**Issue by dannygoldstein** [sncosmo/sncosmo#133]
dgold@volans:~/sncosmo/sncosmo/data/bandpasses$ grep -R ' -' *
csp/Y_texas_DUP_atm.dat:9352.000000 -0.001507
csp/Y_texas_DUP_atm.dat:9356.000000 -0.001559
csp/Y_texas_DUP_atm.dat:9360.000000 -0.001091
csp/Y_texas_DUP_atm.dat:9364.000000 -0.000749
csp/Y_texas_DUP_atm.dat:9368.000000 -0.000571
csp/Y_texas_DUP_atm.dat:9372.000000 -0.000253
csp/V_LC3009_texas_WLcorr_atm.txt:4490.  -5.306651E-5
csp/V_LC3009_texas_WLcorr_atm.txt:6550.  -0.002167748
csp/Y_SWO_TAM_scan_atm.dat:9000.000000 -0.000413
csp/Y_SWO_TAM_scan_atm.dat:9004.000000 -0.000310
csp/Y_SWO_TAM_scan_atm.dat:9008.000000 -0.000183
csp/Y_SWO_TAM_scan_atm.dat:9012.000000 -0.000068
csp/Y_SWO_TAM_scan_atm.dat:9196.000000 -0.000116
csp/Y_SWO_TAM_scan_atm.dat:9200.000000 -0.000229
csp/Y_SWO_TAM_scan_atm.dat:9204.000000 -0.000073
csp/Y_SWO_TAM_scan_atm.dat:11544.000000 -0.000027
csp/Y_SWO_TAM_scan_atm.dat:11548.000000 -0.000101
csp/Y_SWO_TAM_scan_atm.dat:11552.000000 -0.000103
csp/Y_SWO_TAM_scan_atm.dat:11648.000000 -0.000125
csp/Y_SWO_TAM_scan_atm.dat:11652.000000 -0.000142
csp/Y_SWO_TAM_scan_atm.dat:11656.000000 -0.000057
csp/Y_SWO_TAM_scan_atm.dat:11720.000000 -0.000120
csp/Y_SWO_TAM_scan_atm.dat:11724.000000 -0.000317
csp/Y_SWO_TAM_scan_atm.dat:11728.000000 -0.000510
csp/Y_SWO_TAM_scan_atm.dat:11732.000000 -0.000708
csp/Y_SWO_TAM_scan_atm.dat:11736.000000 -0.000901
csp/Y_SWO_TAM_scan_atm.dat:11740.000000 -0.001053
csp/Y_SWO_TAM_scan_atm.dat:11744.000000 -0.001181
csp/Y_SWO_TAM_scan_atm.dat:11748.000000 -0.001431
csp/Y_SWO_TAM_scan_atm.dat:11752.000000 -0.001568
csp/Y_SWO_TAM_scan_atm.dat:11756.000000 -0.001458
csp/Y_SWO_TAM_scan_atm.dat:11760.000000 -0.001373
csp/Y_SWO_TAM_scan_atm.dat:11764.000000 -0.001336
csp/Y_SWO_TAM_scan_atm.dat:11768.000000 -0.001260
csp/Y_SWO_TAM_scan_atm.dat:11772.000000 -0.001157
csp/Y_SWO_TAM_scan_atm.dat:11776.000000 -0.001021
csp/Y_SWO_TAM_scan_atm.dat:11780.000000 -0.000873
csp/Y_SWO_TAM_scan_atm.dat:11784.000000 -0.000806
csp/Y_SWO_TAM_scan_atm.dat:11788.000000 -0.000756
csp/Y_SWO_TAM_scan_atm.dat:11792.000000 -0.000690
csp/Y_SWO_TAM_scan_atm.dat:11796.000000 -0.000594
csp/Y_SWO_TAM_scan_atm.dat:11800.000000 -0.000487
csp/Y_SWO_TAM_scan_atm.dat:11804.000000 -0.000365
csp/Y_SWO_TAM_scan_atm.dat:11808.000000 -0.000237
csp/Y_SWO_TAM_scan_atm.dat:11812.000000 -0.000097
csp/Y_SWO_TAM_scan_atm.dat:11948.000000 -0.000021
csp/Y_SWO_TAM_scan_atm.dat:11952.000000 -0.000096
csp/Y_SWO_TAM_scan_atm.dat:11956.000000 -0.000055
csp/Y_SWO_TAM_scan_atm.dat:11960.000000 -0.000015
csp/Y_SWO_TAM_scan_atm.dat:12016.000000 -0.000056
csp/Y_SWO_TAM_scan_atm.dat:12020.000000 -0.000163
csp/Y_SWO_TAM_scan_atm.dat:12024.000000 -0.000271
csp/Y_SWO_TAM_scan_atm.dat:12028.000000 -0.000390
csp/Y_SWO_TAM_scan_atm.dat:12032.000000 -0.000501
csp/Y_SWO_TAM_scan_atm.dat:12036.000000 -0.000594
csp/Y_SWO_TAM_scan_atm.dat:12040.000000 -0.000653
csp/Y_SWO_TAM_scan_atm.dat:12044.000000 -0.000754
csp/Y_SWO_TAM_scan_atm.dat:12048.000000 -0.000917
csp/Y_SWO_TAM_scan_atm.dat:12052.000000 -0.000941
csp/Y_SWO_TAM_scan_atm.dat:12056.000000 -0.000867
csp/Y_SWO_TAM_scan_atm.dat:12060.000000 -0.000822
csp/Y_SWO_TAM_scan_atm.dat:12064.000000 -0.000755
csp/Y_SWO_TAM_scan_atm.dat:12068.000000 -0.000671
csp/Y_SWO_TAM_scan_atm.dat:12072.000000 -0.000589
csp/Y_SWO_TAM_scan_atm.dat:12076.000000 -0.000512
csp/Y_SWO_TAM_scan_atm.dat:12080.000000 -0.000442
csp/Y_SWO_TAM_scan_atm.dat:12084.000000 -0.000367
csp/Y_SWO_TAM_scan_atm.dat:12088.000000 -0.000295
csp/Y_SWO_TAM_scan_atm.dat:12092.000000 -0.000222
csp/Y_SWO_TAM_scan_atm.dat:12096.000000 -0.000148
csp/Y_SWO_TAM_scan_atm.dat:12100.000000 -0.000076
csp/Y_SWO_TAM_scan_atm.dat:12104.000000 -0.000055
csp/Y_SWO_TAM_scan_atm.dat:12108.000000 -0.000034
csp/Y_SWO_TAM_scan_atm.dat:12112.000000 -0.000012
csp/Y_SWO_TAM_scan_atm.dat:12160.000000 -0.000007
csp/Y_SWO_TAM_scan_atm.dat:12164.000000 -0.000089
csp/Y_SWO_TAM_scan_atm.dat:12168.000000 -0.000169
csp/Y_SWO_TAM_scan_atm.dat:12172.000000 -0.000247
csp/Y_SWO_TAM_scan_atm.dat:12176.000000 -0.000332
csp/Y_SWO_TAM_scan_atm.dat:12180.000000 -0.000415
csp/Y_SWO_TAM_scan_atm.dat:12184.000000 -0.000493
csp/Y_SWO_TAM_scan_atm.dat:12188.000000 -0.000575
csp/Y_SWO_TAM_scan_atm.dat:12192.000000 -0.000653
csp/Y_SWO_TAM_scan_atm.dat:12196.000000 -0.000728
csp/Y_SWO_TAM_scan_atm.dat:12200.000000 -0.000814
csp/Y_SWO_TAM_scan_atm.dat:12204.000000 -0.000727
csp/Y_SWO_TAM_scan_atm.dat:12208.000000 -0.000638
csp/Y_SWO_TAM_scan_atm.dat:12212.000000 -0.000551
csp/Y_SWO_TAM_scan_atm.dat:12216.000000 -0.000456
csp/Y_SWO_TAM_scan_atm.dat:12220.000000 -0.000360
csp/Y_SWO_TAM_scan_atm.dat:12224.000000 -0.000273
csp/Y_SWO_TAM_scan_atm.dat:12228.000000 -0.000184
csp/Y_SWO_TAM_scan_atm.dat:12232.000000 -0.000094
csp/Y_SWO_TAM_scan_atm.dat:12236.000000 -0.000004
csp/H_SWO_TAM_scan_atm.dat:18244.000000 -0.000200
csp/H_SWO_TAM_scan_atm.dat:18248.000000 -0.000424
csp/H_SWO_TAM_scan_atm.dat:18252.000000 -0.000308
csp/H_SWO_TAM_scan_atm.dat:18256.000000 -0.000133
csp/H_SWO_TAM_scan_atm.dat:18260.000000 -0.000037
csp/H_SWO_TAM_scan_atm.dat:18408.000000 -0.000001
csp/H_SWO_TAM_scan_atm.dat:18412.000000 -0.000008
csp/H_SWO_TAM_scan_atm.dat:18416.000000 -0.000012
csp/H_SWO_TAM_scan_atm.dat:18420.000000 -0.000005
csp/H_SWO_TAM_scan_atm.dat:18424.000000 -0.000001
csp/H_SWO_TAM_scan_atm.dat:18428.000000 -0.000014
csp/H_SWO_TAM_scan_atm.dat:18432.000000 -0.000090
csp/H_SWO_TAM_scan_atm.dat:18436.000000 -0.000192
csp/H_SWO_TAM_scan_atm.dat:18440.000000 -0.000196
csp/H_SWO_TAM_scan_atm.dat:18444.000000 -0.000337
csp/H_SWO_TAM_scan_atm.dat:18448.000000 -0.000863
csp/H_SWO_TAM_scan_atm.dat:18452.000000 -0.001269
csp/H_SWO_TAM_scan_atm.dat:18456.000000 -0.001167
csp/H_SWO_TAM_scan_atm.dat:18460.000000 -0.000723
csp/H_SWO_TAM_scan_atm.dat:18464.000000 -0.000272
csp/H_SWO_TAM_scan_atm.dat:18468.000000 -0.000069
csp/H_SWO_TAM_scan_atm.dat:18472.000000 -0.000008
csp/H_SWO_TAM_scan_atm.dat:18476.000000 -0.000000
csp/H_SWO_TAM_scan_atm.dat:18480.000000 -0.000000
csp/H_SWO_TAM_scan_atm.dat:18484.000000 -0.000000
csp/H_SWO_TAM_scan_atm.dat:18488.000000 -0.000000
csp/H_SWO_TAM_scan_atm.dat:18492.000000 -0.000005
csp/H_SWO_TAM_scan_atm.dat:18496.000000 -0.000031
csp/H_SWO_TAM_scan_atm.dat:18500.000000 -0.000067
csp/H_SWO_TAM_scan_atm.dat:18504.000000 -0.000046
csp/H_SWO_TAM_scan_atm.dat:18508.000000 -0.000013
csp/H_SWO_TAM_scan_atm.dat:18512.000000 -0.000013
csp/H_SWO_TAM_scan_atm.dat:18516.000000 -0.000027
csp/H_texas_DUP_atm.dat:18120.000000 -0.000061
csp/H_texas_DUP_atm.dat:18124.000000 -0.000112
csp/H_texas_DUP_atm.dat:18128.000000 -0.000109
csp/H_texas_DUP_atm.dat:18132.000000 -0.000111
csp/H_texas_DUP_atm.dat:18136.000000 -0.000230
csp/H_texas_DUP_atm.dat:18140.000000 -0.000478
csp/H_texas_DUP_atm.dat:18144.000000 -0.000840
csp/H_texas_DUP_atm.dat:18148.000000 -0.001047
csp/H_texas_DUP_atm.dat:18152.000000 -0.000797
csp/H_texas_DUP_atm.dat:18156.000000 -0.000394
csp/H_texas_DUP_atm.dat:18160.000000 -0.000205
csp/H_texas_DUP_atm.dat:18164.000000 -0.000314
csp/H_texas_DUP_atm.dat:18168.000000 -0.000623
csp/H_texas_DUP_atm.dat:18172.000000 -0.000867
csp/H_texas_DUP_atm.dat:18176.000000 -0.001091
csp/H_texas_DUP_atm.dat:18180.000000 -0.001653
csp/H_texas_DUP_atm.dat:18184.000000 -0.001596
csp/H_texas_DUP_atm.dat:18188.000000 -0.000851
csp/H_texas_DUP_atm.dat:18192.000000 -0.000793
csp/H_texas_DUP_atm.dat:18196.000000 -0.001378
csp/H_texas_DUP_atm.dat:18200.000000 -0.001141
csp/H_texas_DUP_atm.dat:18204.000000 -0.000364
csp/H_texas_DUP_atm.dat:18208.000000 -0.000064
csp/H_texas_DUP_atm.dat:18212.000000 -0.000077
csp/H_texas_DUP_atm.dat:18216.000000 -0.000138
csp/H_texas_DUP_atm.dat:18220.000000 -0.000091
csp/H_texas_DUP_atm.dat:18224.000000 -0.000049
csp/H_texas_DUP_atm.dat:18228.000000 -0.000083
csp/H_texas_DUP_atm.dat:18232.000000 -0.000231
csp/H_texas_DUP_atm.dat:18236.000000 -0.000432
csp/H_texas_DUP_atm.dat:18240.000000 -0.000420
csp/H_texas_DUP_atm.dat:18244.000000 -0.000215
csp/H_texas_DUP_atm.dat:18516.000000 -0.000007
csp/H_texas_DUP_atm.dat:18520.000000 -0.000062
csp/H_texas_DUP_atm.dat:18524.000000 -0.000105
csp/H_texas_DUP_atm.dat:18528.000000 -0.000078
csp/H_texas_DUP_atm.dat:18532.000000 -0.000027
csp/H_texas_DUP_atm.dat:18536.000000 -0.000004
csp/H_texas_DUP_atm.dat:18540.000000 -0.000000
csp/H_texas_DUP_atm.dat:18544.000000 -0.000001
csp/H_texas_DUP_atm.dat:18548.000000 -0.000009
csp/H_texas_DUP_atm.dat:18552.000000 -0.000046
csp/H_texas_DUP_atm.dat:18556.000000 -0.000159
csp/H_texas_DUP_atm.dat:18560.000000 -0.000244
csp/H_texas_DUP_atm.dat:18564.000000 -0.000146
csp/H_texas_DUP_atm.dat:18568.000000 -0.000037
csp/H_texas_DUP_atm.dat:18572.000000 -0.000005
csp/H_texas_DUP_atm.dat:18576.000000 -0.000013
csp/H_texas_DUP_atm.dat:18580.000000 -0.000111
csp/H_texas_DUP_atm.dat:18584.000000 -0.000351
csp/H_texas_DUP_atm.dat:18588.000000 -0.000460
csp/H_texas_DUP_atm.dat:18592.000000 -0.000308
csp/H_texas_DUP_atm.dat:18596.000000 -0.000122
csp/H_texas_DUP_atm.dat:18600.000000 -0.000023
csp/H_texas_DUP_atm.dat:18604.000000 -0.000001
csp/H_texas_DUP_atm.dat:18608.000000 -0.000002
csp/H_texas_DUP_atm.dat:18612.000000 -0.000030
csp/H_texas_DUP_atm.dat:18616.000000 -0.000208
csp/H_texas_DUP_atm.dat:18620.000000 -0.000593
csp/H_texas_DUP_atm.dat:18624.000000 -0.000821
csp/H_texas_DUP_atm.dat:18628.000000 -0.000659
csp/H_texas_DUP_atm.dat:18632.000000 -0.000320
csp/H_texas_DUP_atm.dat:18636.000000 -0.000248
csp/H_texas_DUP_atm.dat:18640.000000 -0.000265
csp/H_texas_DUP_atm.dat:18644.000000 -0.000125
csp/H_texas_DUP_atm.dat:18648.000000 -0.000027
csp/H_texas_DUP_atm.dat:18652.000000 -0.000025
csp/H_texas_DUP_atm.dat:18656.000000 -0.000068
csp/H_texas_DUP_atm.dat:18660.000000 -0.000122
csp/H_texas_DUP_atm.dat:18664.000000 -0.000101
csp/H_texas_DUP_atm.dat:18668.000000 -0.000017
csp/H_texas_DUP_atm.dat:18772.000000 -0.000000
csp/H_texas_DUP_atm.dat:18776.000000 -0.000001
csp/H_texas_DUP_atm.dat:18780.000000 -0.000007
csp/H_texas_DUP_atm.dat:18784.000000 -0.000021
csp/H_texas_DUP_atm.dat:18788.000000 -0.000064
csp/H_texas_DUP_atm.dat:18792.000000 -0.000160
csp/H_texas_DUP_atm.dat:18796.000000 -0.000197
csp/H_texas_DUP_atm.dat:18800.000000 -0.000222
csp/H_texas_DUP_atm.dat:18804.000000 -0.000280
csp/H_texas_DUP_atm.dat:18808.000000 -0.000172
csp/H_texas_DUP_atm.dat:18812.000000 -0.000047
csp/H_texas_DUP_atm.dat:18816.000000 -0.000034
csp/H_texas_DUP_atm.dat:18820.000000 -0.000120
csp/H_texas_DUP_atm.dat:18824.000000 -0.000343
csp/H_texas_DUP_atm.dat:18828.000000 -0.000484
csp/H_texas_DUP_atm.dat:18832.000000 -0.000410
csp/H_texas_DUP_atm.dat:18836.000000 -0.000310
csp/H_texas_DUP_atm.dat:18840.000000 -0.000146
csp/H_texas_DUP_atm.dat:18844.000000 -0.000032
csp/H_texas_DUP_atm.dat:18848.000000 -0.000040
csp/H_texas_DUP_atm.dat:18852.000000 -0.000142
csp/H_texas_DUP_atm.dat:18856.000000 -0.000229
csp/H_texas_DUP_atm.dat:18860.000000 -0.000248
csp/H_texas_DUP_atm.dat:18864.000000 -0.000387
csp/H_texas_DUP_atm.dat:18868.000000 -0.000377
csp/H_texas_DUP_atm.dat:18872.000000 -0.000196
csp/H_texas_DUP_atm.dat:18876.000000 -0.000326
csp/H_texas_DUP_atm.dat:18880.000000 -0.000775
csp/H_texas_DUP_atm.dat:18884.000000 -0.001143
csp/H_texas_DUP_atm.dat:18888.000000 -0.001141
csp/H_texas_DUP_atm.dat:18892.000000 -0.000929
csp/H_texas_DUP_atm.dat:18896.000000 -0.000667
csp/i_texas_WLcorr_atm.txt:8640.  -0.001172514
csp/V_LC3014_texas_WLcorr_atm.txt:4490.  -4.896312E-5
csp/V_LC3014_texas_WLcorr_atm.txt:6550.  -0.001763015
csp/r_texas_WLcorr_atm.txt:7180.  -0.004337063

**Comment by kbarbary** [comment]
Presumably this is due to measurement uncertainty in CSP's bandpass measurements.

Obviously this is unphysical, but I don't *think* this should cause any problems for sncosmo: I don't think any of the code assumes that transmissions are non-negative. Have you observed any problems from this?

**Comment by kbarbary** [comment]
Closing as unactionable.
