### ISSUE TITLE
extinction laws in tensorflow

### ISSUE THREAD

**Issue by dannygoldstein** [sncosmo/sncosmo#139]
@kbarbary,

I am working on implementing some extinction laws in tensorflow, to enable gradients of a likelihood function to be computed with respect to reddening parameters.

Is this something you would be interested in incorporating into your universe of supernova cosmology utilities?

**Comment by kbarbary** [comment]
FYI I've recently factored extinction laws in sncosmo into a separate package:

http://github.com/kbarbary/extinction
http://extinction.readthedocs.io

The plan (not yet done) is to make this an sncosmo dependency or bundle it. I've spent some time optimzing the cython code there. It doesn't yet have gradients but it was something I've had in mind. Gradients in A_V are fairly trivial of course. Gradients in R_V are easy in some cases (CCM, O'Donnell, Calzetti) and nearly impossible in others (Fitzpatrick 99).

Not sure what you had in mind for tie-in, but it's likely that tensorflow is too big of a dependency for either `extinction` or `sncosmo` to take on. Can tensorflow use hand-written gradient functions if you provide them?

**Comment by rbiswas4** [comment]
Quick question about this to both of you:

- Are these due to the fact that you are trying to fit extinction parameters to the data around the CCM etc. values? ie. because you are (correctly) treating those measurements as priors on the extinction parameters, while these are part of the current likelihood function?
- If so, is there any estimate/understanding/intuition of how much tighter/different the current posterior is compared to the measurements?

**Comment by dannygoldstein** [comment]
OK, just wanted to gauge interest. 

Tensorflow can use hand-written gradient functions if you implement your target function as a `tf.Operation` in C++. Details here:

https://www.tensorflow.org/versions/r0.9/how_tos/adding_an_op/index.html#define-the-ops-interface

A simpler implementation strategy is to define your reddening laws directly in python and compose them out of simpler tensorflow operations that already have gradients defined. e.g., 

```python
def ccm89(wave, ebv, r_v):
   # wave, ebv, and r_v are all tensors
   # do some basic tensorflow operations on the tensors like add, multiply, etc.
   return transmission_tensor
```

Since add, multiply, etc already have gradients defined, the gradient of a function (e.g., a likelihood) that depends on `transmission_tensor` with respect to `ebv`, or `r_v`  computed trivially by autodiff on the tensorflow operations inside `ccm89`.

Danny

**Comment by dannygoldstein** [comment]
@rbiswas4,

> Are these due to the fact that you are trying to fit extinction parameters to the data around the CCM etc. values? ie. because you are (correctly) treating those measurements as priors on the extinction parameters, while these are part of the current likelihood function?

Yes.

> If so, is there any estimate/understanding/intuition of how much tighter/different the current posterior is compared to the measurements?

Not yet.

**Comment by dannygoldstein** [comment]
My idea for a tie in was that you could expose an (optional) tensorflow API in your extinction module.

Danny

**Comment by rbiswas4** [comment]
@dannygoldstein Thanks.

**Comment by dannygoldstein** [comment]
@kbarbary, there is also a third way:

https://github.com/tensorflow/tensorflow/issues/1095

**Comment by kbarbary** [comment]
Closing this as not actionable from sncosmo end. If anything, the tie-in would be adding gradient calculation in the extinction module.
