### ISSUE TITLE
BUG: `mcmc_lc` calls unresolved mathlib function when priors are specified

### ISSUE THREAD

**Issue by dannygoldstein** [sncosmo/sncosmo#143]
When you pass something to `priors` in `fitting.mcmc_lc`, the code attempts to call `math.log`, but `math` is never imported.

**Comment by rbiswas4** [comment]
Is this then a bug in the release 1.2.3 ?

**Comment by dannygoldstein** [comment]
Yeah.

On Fri, Jul 1, 2016 at 6:10 PM, rbiswas4 <notifications@github.com> wrote:

> Is this then a bug in the release 1.2.3 ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sncosmo/sncosmo/issues/143#issuecomment-230075508>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ACpC4CVQlkVstviIIjWqjhUE5vYM4y5oks5qRbqAgaJpZM4JDkVM>
> .
>



-- 
Danny Goldstein
http://astro.berkeley.edu/~dgold/
