### ISSUE TITLE
Downloading 2011fe model fails

### ISSUE THREAD

**Issue by GiantJ** [sncosmo/sncosmo#153]
The link to snf-2011fe model seems broken, could you update it? Thx!

**Comment by kbarbary** [comment]
Thanks for reporting. It looks like the model data have moved (or been removed) on the nearby supernova factory website. I'll try to find out where they've moved to.

**Comment by kbarbary** [comment]
This should be fixed now.

**Comment by GiantJ** [comment]
Yes, thank you so much!
