### ISSUE TITLE
Change between v1.3.2 and v1.4.0

### ISSUE THREAD

**Issue by AlexGKim** [sncosmo/sncosmo#165]
There is a change in the results of v.1.3.2 and 1.4.0.  I am calculating the extinction of a Hsiao template at peak magnitude due to Fitzpatrick dust in a tophat filter.  The different versions give answers that differ by 0.08 mag.

Here is the code.

```python
#!/usr/bin/env python
import numpy
import sncosmo

print sncosmo.__version__

lams = numpy.array([4795.35,5780.60])

name='V'

synbands=sncosmo.Bandpass(lams, [1.,1.], name='tophat'+name)

model_nodust = sncosmo.Model(source='hsiao')
flux_nodust = model_nodust.bandflux(synbands,0.)

av=1.75
ebv=1.75

dust = sncosmo.F99Dust(r_v=av/ebv)
dust.set(ebv=ebv)
model = sncosmo.Model(source='hsiao', effects=[dust], effect_names=['host'],
                      effect_frames=['rest'])
print 2.5*numpy.log10(model.bandflux(synbands,0)/flux_nodust)
```

The outputs are 

```
(testold) tibia:gerard akim$ ./test.py 
1.3.2
-1.79064199162
```

```
(testnew) tibia:gerard akim$ ./test.py
1.4.0
-1.87486161673
```

**Comment by AlexGKim** [comment]
`#!/usr/bin/env python
import numpy
import sncosmo

print sncosmo.__version__

lams = numpy.array([4795.35,5780.60])

name='V'

synbands=sncosmo.Bandpass(lams, [1.,1.], name='tophat'+name)

model_nodust = sncosmo.Model(source='hsiao')
flux_nodust = model_nodust.bandflux(synbands,0.)

av=1.75
ebv=1.75

dust = sncosmo.F99Dust(r_v=av/ebv)
dust.set(ebv=ebv)
model = sncosmo.Model(source='hsiao', effects=[dust], effect_names=['host'], effect_frames=['rest'])
print 2.5*numpy.log10(model.bandflux(synbands,0)/flux_nodust)
`

**Comment by kbarbary** [comment]
The new version should be more correct. Formerly, the grid used for the synthetic photometry integral was defined by the bandpass's grid. In this case, that's only two points, leading to a large numerical error.

In v1.4.0, the grid used for synthetic photometry is a fixed spacing regardless of the bandpass's grid. The default is 5 Angstroms.

You can test the dependence on the spacing used by changing the (currently undocumented, not public) value `sncosmo.models.MODEL_BANDFLUX_SPACING`.

For example, setting `sncosmo.models.MODEL_BANDFLUX_SPACING  = 0.1`, I get `-1.87485764725` for your test. So, a spacing of 5.0 seems to give a pretty accurate result.

Note that many of the built-in bandpasses were defined on a grid of about 5 Angstroms anyway, so in most cases, there should not be such a big change.

**Comment by AlexGKim** [comment]
Got it, thanks.
