### ISSUE TITLE
SALT2 version

### ISSUE THREAD

**Issue by AlexGKim** [sncosmo/sncosmo#177]
I would like to inquire what version of the SALT2 training is default.  It would be good to have this information available in the class.

**Comment by kbarbary** [comment]
The default version for any source is the highest version (for that source) listed on the [Built-in sources page](https://sncosmo.readthedocs.io/en/v1.4.x/source-list.html). In this case, it is version 2.4(*).

This is accessible from code as well:

```python
>>> model = sncosmo.Model('salt2')

>>> print(model)
<Model at 0x7f8dd7dcf358>
source:
  class      : SALT2Source
  name       : 'salt2'
  version    : 2.4
  phases     : [-20, .., 50] days
  wavelengths: [2000, .., 9200] Angstroms
parameters:
  z  = 0.0
  t0 = 0.0
  x0 = 1.0
  x1 = 0.0
  c  = 0.0

>>> model.source.version
'2.4'
```

(*) Somewhat confusingly, this perhaps should be called SALT2 version 4.0: it is the 'salt2-4' tarball, not 'salt2-2-4' (which doesn't exist). The paper reference is given on the built-in sources page, which should disambiguate the meaning of the version number.

**Comment by AlexGKim** [comment]
Ah, I was mistakenly trying to find that information in sncosmo.SALT2Source.  Which I see is the wrong place since that class accommodates multiple versions.

**Comment by kbarbary** [comment]
Right, as long as the versions function the same way (as long as the code needed to implement them is the same), they're represented by a single class. The same way that multiple sources are implemented with the `TimeSeriesSource` class.
