### ISSUE TITLE
LSST bandpasses

### ISSUE THREAD

**Issue by AlexGKim** [sncosmo/sncosmo#181]
This is a request to add LSST bandpasses to the set of "included" bandpasses.  sncosmo is being used for LSST simulations.  I would do this myself, but I assume Rahul has already implemented all of them.

**Comment by rbiswas4** [comment]
I thought @kbarbary has already included them.

**Comment by kbarbary** [comment]
Already done on master. Nearing a new release, but will still be a few weeks.

**Comment by AlexGKim** [comment]
I don’t see them listed here:

http://sncosmo.readthedocs.io/en/v1.4.x/bandpass-list.html

**Comment by kbarbary** [comment]
You linked to the docs for the release version, v1.4

**Comment by kbarbary** [comment]
http://sncosmo.readthedocs.io/en/latest/bandpass-list.html#lsst
