### ISSUE TITLE
Could _download_url give a more helpful error message?

### ISSUE THREAD

**Issue by danielsf** [sncosmo/sncosmo#188]
I am with the LSST simulations team.  We have started shipping sncosmo as a part of our simulations software package.  Occasionally, users experience failures when sncosmo tries to download data (e.g. the SALT models).  Often, this is because they are behind a firewall that is blocking their access to the data server.  The error message, however, is not very explanatory

```
  File "/Users/bxin/lsst_stack/DarwinX86/sncosmo/12.0-1-g5e70e90+2/lib/python/sncosmo-1.3.0-py2.7-macosx-10.6-x86_64.egg/sncosmo/utils.py", line 247, in _download_file

    raise URLError(e)

URLError: <urlopen error timed out>
```

It would be very helpful if the error message included the URL that timed out/failed so that we can help users diagnose the problem with their firewall.

Thanks.

**Comment by kbarbary** [comment]
Yes I agree. I recently added this info for HTTP 404s in e244224.

Looks like this is a socket.timeout that is getting reraised as a URLError in  [this section of code](https://github.com/sncosmo/sncosmo/blob/87d34bc522eda4dd02b911bab2ac977c0eda62f0/sncosmo/utils.py#L271-L276). I think all that needs to be done is add a line before `raise URLError(e)` like

```python
e.args = ('<some URL> timed out',)
```

**Comment by kbarbary** [comment]
PS: To entirely avoid this sort of thing, one can pre-download all the data files you want to use (on some machine not behind a firewall) and then package up the data directory and unpack it on the target machine (ensuring that the path to the data directory is set correctly). sncosmo doesn't try to use the network at all if it finds the file it's looking for locally.

**Comment by danielsf** [comment]
Great.  Thanks, Kyle.  Rahul and I just had a conversation similar to your "pre-download the data" suggestion.  Is it obvious how to tell sncosmo where the data lives?

**Comment by kbarbary** [comment]
https://sncosmo.readthedocs.io/en/v1.4.x/configuration.html#configuring-the-directories

On master, you should also be able to use an `SNCOSMO_DATA_DIR` environment variable, which takes precedence if defined.
