### ISSUE TITLE
links in documentation to source code

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#194]
Reference API in the docs used to have links to the source code. This is no more the case (latest,. If this is simply an oversight, and not due to new technical issues, it would be good to get this feature back.

**Comment by kbarbary** [comment]
This got left out when I switched to the RTD theme. Addressed in adf3dfb. Link now goes to github source rather than an HTML copy.

Should show up in the online docs once the build completes. :crossed_fingers:

**Comment by kbarbary** [comment]
Looks like it worked.

**Comment by rbiswas4** [comment]
Thanks! That does it. I suppose it will be harder to get this to work on the 1.v4 documentation?

**Comment by kbarbary** [comment]
Wouldn't be that hard. I *think* you'd just need to `git cherry-pick` the above-mentioned commit onto the `v1.4.x` branch. But v1.5.0 will be released "soon" so I'm not going to bother. PRs are always accepted though. ;)
