### ISSUE TITLE
Nan values returned by `flux`

### ISSUE THREAD

**Issue by dannygoldstein** [sncosmo/sncosmo#200]
When I try to create a `TimeSeriesSource` with the following `phase`, `wave`, and `flux`, arrays, which contain no `nan` elements, the `flux` method of the resulting source always returns `nan`, for any phase/wave value.

The arrays can be downloaded here:

http://w.astro.berkeley.edu/~dgold/static/nan_source.pkl

They can be loaded into memory and turned into a source by doing

```python
import pickle, sncosmo
phase, wave, ts = pickle.load(open('nan_source.pkl','rb'))
source = sncosmo.TimeSeriesSource(phase, wave, ts)
```

and you will see for any phase or wave, e.g.,

```python
source.flux(0., 4000.) # returns nan
```

why is this happening?

**Comment by kbarbary** [comment]
This might have something to do with it?
```python
In [5]: ts.min()
Out[5]: -inf

In [6]: ts.max()
Out[6]: inf

```
