### ISSUE TITLE
HTTP Error when attempting to retrieve Kepler filter curve

### ISSUE THREAD

**Issue by ssagear** [sncosmo/sncosmo#219]
I see this error:

```python
HTTPError: HTTP Error 403: Forbidden. requested URL: u'https://keplergo.arc.nasa.gov/kepler_response_hires1.txt'
```
when attempting to retrieve the Kepler filter curve for the first time in

```python
bandflux = model.bandflux('Kepler', self.time)
```

A workaround is to download this file into ~/.astropy/cache/sncosmo/bandpasses/kepler.

**Comment by kbarbary** [comment]
I can reproduce this problem. Weird. I wonder if the Kepler GO server policy changed in some way to reject automated downloads? Maybe @barentsen or @gully knows...

**Comment by kbarbary** [comment]
The problem seems related to L230-235 of utils.py:
```python
        # Pretend to be a web browser (IE 6.0). Some servers that we download
        # from forbid access from programs.
        headers = {'User-Agent': 'Mozilla/5.0',
                   'Accept': ('text/html,application/xhtml+xml,'
                              'application/xml;q=0.9,*/*;q=0.8')}
        req = Request(remote_url, headers=headers)
```
Without these headers, the download succeeds (at least with `urllib.request.urlretrieve()`).

**Comment by kbarbary** [comment]
Thanks Geert. I added the file directly to sncosmo.github.io, so it should be working now. Thanks for reporting, @ssagear!
