### ISSUE TITLE
Python 3.7 conda package

### ISSUE THREAD

**Issue by kboone** [sncosmo/sncosmo#228]
For whatever reason the conda packages for sncosmo aren't being built for python 3.7. Could you enable those builds? I'm not sure what needs to be done for this, but I can help if pointed in the right direction.

**Comment by kbarbary** [comment]
I recently released a new version 1.7.1 on PyPI that has yet to be built for conda. Hopefully it will get built for Python 3.7 when that happens. See conda-forge/sncosmo-feedstock#8

**Comment by kbarbary** [comment]
Should be available now.
