### ISSUE TITLE
Determining decline rate from fitted model

### ISSUE THREAD

**Issue by djperrefort** [sncosmo/sncosmo#233]
I'd like to calculate the B band decline rate from a fitted model returned by `sncosmo.fit_lc` but I'm unclear on how to retrieve this information from an instance of the `sncosmo.models.Model` class. 

My initial thought was to determine the absolute B-band magnitude at peak using `fitted_model.source_peakabsmag('bessellb', 'AB')` and then find the difference from the absolute magnitude 15 days later. Unfortunately, I only see methods for calculating the **apparent** magnitude in the **observer** frame (`fitted_model.bandmag`). I also don't see any references to the decline rate in the documentation.

Is there a preferred way to calculate the decline rate with `sncosmo`?

**Comment by kbarbary** [comment]
You can access the `source` part of the model to do this, something like so:
```python
peakphase = fitted_model.source.peakphase('bessellb')
m1 = fitted_model.source.bandmag('bessellb', 'ab', peakphase)
m2 = fitted_model.source.bandmag('bessellb', 'ab', peakphase + 15)
```

Perhaps surprisingly, I've never heard anyone wanting to calculate this. I guess people typically just want to use the model parameter that controls the light curve width (`x1` for SALT2 or `delta` for MLCS2k2).

**Comment by djperrefort** [comment]
Great - Thank you @kbarbary

**Comment by kbarbary** [comment]
No problem!
