### ISSUE TITLE
Free Propagation Effects Losing Information During Fitting?

### ISSUE THREAD

**Issue by jpierel14** [sncosmo/sncosmo#235]
I'm adding a free propagation effect (dust) to a model, then fitting it to some data with nest_lc. If I set the dust redshift for the free frame to a constant, then after fitting that value has been set to zero. Am I just setting the redshift wrong or misusing this in some way? Or is something going on under the hood incorrectly?

  
    salt2_model=sncosmo.Model('salt2',effects=[sncosmo.CCM89Dust()],effect_names= 
                 ['dust'],effect_frames=['free'])
    salt2_model.set(**{'z':.5,'dustr_v':3.1,'dustz':.2})
    print(salt2_model.param_names,salt2_model.parameters)
    res,fit=sncosmo.nest_lc(sncosmo.load_example_data(),salt2_model,vparam_names= 
       ['x0','x1','t0','c','dustebv'], bounds={'x1':(-2,2),'c':(0,1),'dustebv' 
                    (0,.1)},guess_amplitude_bound=True)
    print(fit.param_names,fit.parameters)

Output:

    (['z', 't0', 'x0', 'x1', 'c', 'dustz', 'dustebv', 'dustr_v'], array([0.5, 0. , 1. , 0. , 0. , 0.2, 0. , 3.1]))

    (['z', 't0', 'x0', 'x1', 'c', 'dustz', 'dustebv', 'dustr_v'], array([5.00000000e-01, 
       5.51004165e+04, 1.32536779e-05, 3.57170512e-01,
       1.97272852e-01, 0.00000000e+00, 5.12593116e-02, 3.10000000e+00]))

**Comment by kbarbary** [comment]
Unless I'm missing something, it looks like a bug. Reviewing the surrounding code, it's not immediately obvious what the cause is. I'll try to get a chance to debug, but if you want to take a try, I'd start by trying to figure out at which point in `fit_lc` the value changes from 0.2 to 0.0.

**Comment by kbarbary** [comment]
Thanks for reporting!

**Comment by jpierel14** [comment]
Okay I've figured out where the bug is, but not sure why it's happening. It's at the top of each fitting routine:

    print(model.parameters)
    model=copy.copy(model)
    print(model.parameters)
    
Outputs:

    [0.5 0.  1.  0.  0.  0.2 0.  3.1]
    [0.5 0.  1.  0.  0.  0.  0.  3.1]

Very strange...something to do with the model structure and what gets copied? Something shallow isn't being updated?

**Comment by kbarbary** [comment]
I think there is an "oversight" (nice way to say :bug:) in the implementation of `Model.__copy__`, which gets called when you do `copy.copy(model)`:
```
    def __copy__(self):
        new = Model(self._source,
                    effects=self._effects,
                    effect_names=self._effect_names,
                    effect_frames=self._effect_frames)
        new._parameters[0:2] = self._parameters[0:2]
        return new
```
The line `new._parameters[0:2] = self._parameters[0:2]`  exists to copy over all parameter values that are not "owned" by the source or effects. The Model itself "owns" the first two parameters: `z` and `t0`. This was correct before the "free" option was added to effects. Now the model additionally owns the redshift for any effect that is "free", but this line was not updated to reflect that. I think it should work to just change the line to
```
new._parameters[:] = self._parameters
```
which will copy all the parameters, whether they absolutely need to be copied or not. Can you try that out and see if it fixed the problem?

**Comment by jpierel14** [comment]
That certainly appears to do it!

**Comment by kbarbary** [comment]
Want to make a PR with the fix?

**Comment by jpierel14** [comment]
Sure, done.
