### ISSUE TITLE
sncosmo crashes with scipy 1.3

### ISSUE THREAD

**Issue by MickaelRigault** [sncosmo/sncosmo#237]
Hello, 

I would like to let you know that sncosmo is not anymore compatible with the scipy. Which is a problem. It works for scipy<1.2

`from scipy.interpolate import splmake` does not work anymore.

Scipy 1.3 doc says:

scipy.interpolate changes
_Functions from scipy.interpolate (spleval, spline, splmake, and spltopp) and functions from scipy.misc (bytescale, fromimage, imfilter, imread, imresize, imrotate, imsave, imshow, toimage) have been removed. The former set has been deprecated since v0.19.0 and the latter has been deprecated since v1.0.0. Similarly, aliases from scipy.misc (comb, factorial, factorial2, factorialk, logsumexp, pade, info, source, who) which have been deprecated since v1.0.0 are removed. SciPy documentation for v1.1.0 can be used to track the new import locations for the relocated functions._

**Comment by kbarbary** [comment]
Thanks for reporting Mickael! I believe the fix is to use the spline classes in scipy.interpolate (which I didn't originally do because it was somewhat slower at the time).

If anyone has time to fix and submit a pr, that would be great.

**Comment by kbarbary** [comment]
After actually looking at the code, it looks like we're not using `splmake` and `spleval` any more, but the import was still there.
