### ISSUE TITLE
Bandpass downloads from stsci not working

### ISSUE THREAD

**Issue by koconnor4** [sncosmo/sncosmo#246]
Is it possible that the throughput website was updated recently? The urls in builtins.py for ACS & WFC3 bandpasses point to webpages without the data available causing it to download the webpage instead of the tables. 

It looks like the tables are located in zip files [here](http://www.stsci.edu/hst/instrumentation/wfc3/performance/throughputs), so maybe be best to just host these on sncosmo.github.io?

**Comment by kbarbary** [comment]
Thanks for reporting! I've been traveling and won't be back with my laptop for a while. If someone is interested in giving this sooner, you could submit a PR to sncosmo/sncosmo.github.io adding the data files in the appropriate place under the `data/filters` directory and updating the `redirects.json` file to remove the redirects to the STScI site for the filters.

Alternatively, if anyone knows where they are moved to, we could just change the redirect address.

**Comment by jpierel14** [comment]
WFC3 filters should be fixed by the pull requests above, ACS WFC filters still won't work, until someone can find the throughput tables.

**Comment by kbarbary** [comment]
Hopefully fixed now. :crossed_fingers: Please check that it works for you!
