### ISSUE TITLE
Automatically downloaded ACS WFC filter profiles cannot be loaded by `astropy.io.ascii`

### ISSUE THREAD

**Issue by shiaki** [sncosmo/sncosmo#248]
https://github.com/sncosmo/sncosmo/blob/c9380b93b787f840d8e57a1e44f704585d70e90f/sncosmo/builtins.py#L176

**Problem description**

The program downloads ACS WFC filter profiles when they are not in the local cache. However, the downloaded filter profiles cannot be loaded by `astropy.io.ascii` (throws a `InconsistentTableError` or `ValueError`). They look like valid HTML files but having no tabulated filter transmission curves.

It is likely that the upper-stream data sources have changed and the URLs should be updated, or a mirror should be created just like other filter profiles.

**Comment by kbarbary** [comment]
Similar to #246 I think.

**Comment by kbarbary** [comment]
This should be fixed now. :crossed_fingers: Please do check and go ahead and close if it seems to be fixed for you!
