### ISSUE TITLE
Package doesn't work with Astropy 4

### ISSUE THREAD

**Issue by timj** [sncosmo/sncosmo#255]
As described in #225 sncosmo breaks with Astropy 4 because `astropy.extern` no longer includes `six`. I see that the code on master still tries to import `six`.

I couldn't find an explicit issue on this and I saw that #225 was closed.  I'm not entirely sure which approach you want to take to fix things but in theory I can do a pull request if you give me some guidance.

**Comment by timj** [comment]
@rbiswas4  It looks like `six` was mostly removed but `astropy.extern.six` is still used in 3 test files.

**Comment by kbarbary** [comment]
sncosmo v2.0 should have removed all `six` usage. A PR to clean up ones I missed would be appreciated! I can make a new release afterwards.

**Comment by kboone** [comment]
I made a PR for this.

**Comment by kbarbary** [comment]
solved by #258
