### ISSUE TITLE
New release of sncosmo Please

### ISSUE THREAD

**Issue by dannygoldstein** [sncosmo/sncosmo#256]
Kyle, can you please make a new release of sncosmo, so that the ZTF filter transmissions can be made available standard?

Thanks,
Danny

**Comment by kbarbary** [comment]
I just made a PR to fix a build issue: #257, Also need to resolve #255 before releasing a new version.  Want to do a little PR for that?

**Comment by kbarbary** [comment]
Update: I will have time to do a new release on Sunday Feb 8 (out of town until then). I hope to get #251 in before then too.

**Comment by kbarbary** [comment]
v2.1.0 has been released.
