### ISSUE TITLE
Cython should be a dependency of sncosmo

### ISSUE THREAD

**Issue by dannygoldstein** [sncosmo/sncosmo#270]
Cython is needed to compile salt2utils, but is not marked as an sncosmo dependency. Can this be added to the list of requirements (and setup.py install_requires) so that sncosmo builds successfully from pip on environments without cython already installed ?

**Comment by dannygoldstein** [comment]
Ah OK I see it is handled by `pyproject.toml`, so it gets installed via pip if necessary. However, when I list `sncosmo` as an `install_requires` dependency of another package, then call that package's `python setup.py install`, it complains about `Cython` not being installed when trying to cythonize `salt2utils`. @kbarbary  do you know of Any way around this ?

**Comment by kbarbary** [comment]
Does it work if you call `pip install .` for the project instead of `python
setup.py install`?

**Comment by dannygoldstein** [comment]
That works, but is there anyway to have setuptools pick up pyproject.toml?

It looks like they have labeled it a wontfix, 

https://github.com/pypa/setuptools/issues/651

does this mean `pip install .` is now the best way to install packages (over `python setup.py install`)?

**Comment by dannygoldstein** [comment]
Wow, apparently this is the case! The recommended way to install local packages now is to use pip instead of setuptools. Learn something new every day... 

<img width="801" alt="Screen Shot 2020-06-01 at 10 19 24 PM" src="https://user-images.githubusercontent.com/2769632/83472768-04a0a100-a456-11ea-9fab-c120c71f1827.png">

Reference: https://pip.pypa.io/en/stable/reference/pip_install/#install-editable
