### ISSUE TITLE
Adding V19 core collapse templates

### ISSUE THREAD

**Issue by maria-vincenzi** [sncosmo/sncosmo#271]
Hello,
Last year I published a new library of 60ish core collapse templates.
This is the github folder where the templates can be downloaded: [https://github.com/maria-vincenzi/PyCoCo_template](https://github.com/maria-vincenzi/PyCoCo_template)
and this is the reference paper: [https://arxiv.org/abs/1908.05228](https://arxiv.org/abs/1908.05228)

It is pretty straightforward to upload the templates in sncosmo (using class TimeSeriesSource) and to register them (using sncosmo.register).  Here is an example of how you can do this [https://github.com/maria-vincenzi/PyCoCo_templates/blob/master/register_SNcosmo.py](https://github.com/maria-vincenzi/PyCoCo_templates/blob/master/register_SNcosmo.py)

However, I received several requests about adding the templates to the list of built-in models in sncosmo. Is this possible? How can we do this?

Thanks
Maria

**Comment by jpierel14** [comment]
Hey Maria, I did this for my P18 models as well so the process should be easily reproducible by taking a look at https://github.com/sncosmo/sncosmo.github.io/pull/11 and https://github.com/sncosmo/sncosmo/pull/229. If you want I could just download the repository and set up the pull request myself, or you can follow what I did there to make your own. You just need to follow the directory format you'll see in the io pull request (or just see [here](https://github.com/sncosmo/sncosmo.github.io/tree/master/data/models)), and then change the builtins file in the sncosmo directory to match the second pull request above. 

It'll be good to get those models in here!

**Comment by maria-vincenzi** [comment]
Great! thanks!
I created the two pull-requests!
So this should be sorted soon!

**Comment by kboone** [comment]
These are now available in the v2.2.0 release from #272
