### ISSUE TITLE
sdss data unit

### ISSUE THREAD

**Issue by joaofrancafisica** [sncosmo/sncosmo#274]
Hello,

I have a data set of the II survey of sdss. The flux unit is given in microJansky. I would like to know if I can make the fit in sncosmo using this unit. In this case, would zeropoint be: 2.5log(3631*10^6jy) ~ 24 for all?

Thanks for your support.

João.

**Comment by rbiswas4** [comment]
Hi Joāo,

Yes, zp = 2.5*log10(3631* 10**6) is the correct expression for converting microJansky fluxes to AB magnitudes. 

You can also use `~astropy` for this :
```
import astropy.units as u
u.microjansky.to(u.ABmag)
>>> 23.9
```
You can also use the zero point directly or the astropy method to convert AB magnitudes to `microjansky` or `nanojansky`.
```(0*u.ABmag).to(u.microjansky)``` Thanks!

**Comment by joaofrancafisica** [comment]
Thank you for your answer.

To fit a light curve in sncosmo, I would put this same zeropoint for all bands in the data set, right? I have this doubt because this definition of ab mag system is a monochromatic definition and sncosmo do a integration over the band even for a zeropoint.

**Comment by kboone** [comment]
Yes, that will work. Given a band and a source that you want to compute photometry for, `sncosmo` integrates the flux of the source over that band to get a flux `f_source`. It then does a second integration of the flux from a reference source to get `f_ref`. The flux value in a given magnitude system is simply `f_source / f_ref`. The AB mag reference source is a constant flux in f_nu (which isn't monochromatic!).

This value is often very small/large, so the zeropoint is simply a scaling by `10**(-0.4 * zp)` to make the fluxes more manageable numbers.

**Comment by kbarbary** [comment]
Just to follow on to what @kboone said, the fact that the dataset has units of Janskys is itself misleading: Jansky is a unit of spectral flux *density*, but in optical photometry, we only measure the integral of spectral flux density over some bandpass.

So if we don't actually measure spectral flux density, what does it *actually* mean when the SN flux is reported as X Jy by SDSS? The intended meaning is that the SN's spectral flux density *integrated over the bandpass* is X times greater than a 1 Jy source *integrated over the bandpass*.

This is why sncosmo integrates both the source model and reference spectrum over the bandpass.
