### ISSUE TITLE
Can light curve fit parameters be used in a cosmological fit?

### ISSUE THREAD

**Issue by joaofrancafisica** [sncosmo/sncosmo#275]
Hello again,

I would like to know if I could use light curve fit parameters given by sncosmo directly in a cosmological fit (aside from bias correction, and second order erros). I saw that the color factor used in sncosmo is a little different from salt2 (10**-.4cCl compared to exp(cCl)). I tried to do a cosmological fit and omega_m and omega_l minimized doesn't make sense.

Thanks,

João.

**Comment by kboone** [comment]
You should be able to do this. There are several groups that are using `sncosmo` for cosmological analyses. I believe that @kbarbary validated the `sncosmo` SALT2 fits against `snfit`, so you should get nearly identical results with either fitter.
