### ISSUE TITLE
New release including `Spectrum` class

### ISSUE THREAD

**Issue by sam-dixon** [sncosmo/sncosmo#277]
I've found the new `Spectrum` class to be super useful, but right now I can only use it if I build sncosmo from source or pip install from Github. It'd be nice to have it installable through the standard pip/conda channels, as well as to be able to indicate a dependency on this version down the line. 

Can we get a new release that includes the rewritten `Spectrum` class?

**Comment by kboone** [comment]
`sncosmo` v2.2.0 was just released and contains those commits. It is on pypi now and should be on conda shortly.
