### ISSUE TITLE
A unified amplitude system for models

### ISSUE THREAD

**Issue by QNWang93** [sncosmo/sncosmo#284]
Hi, it seems that the amplitude parameter in model are not unified yet. For some model, setting `amplitude=1` gives reasonable magnitude, while for some others, 10^-9 seems to be the right value. In most cases I know I can use `set_peakmagnitude` to set an empirical value, but in many other cases I want to use the intrinsic value in models. Is there an easy way to find right amplitude value for each model?

**Comment by rbiswas4** [comment]
It is correct that the amplitude is not uniform across models. Even if it was unified though, the magnitudes would not be correct for different redshifts. Secondly, the intrinsic brightnesses are not known for the models

For a particular case, I usually set  this to an absolute magnitude using:
https://github.com/sncosmo/sncosmo/blob/6308afc08e7301924850f808c1c0dac9c7a1e7c7/sncosmo/models.py#L1556

Note that this requires setting (or accepting a default) cosmology as well.

**Comment by QNWang93** [comment]
Thank you for information!
