### ISSUE TITLE
sncosmo.flatten_result raises AttributeError

### ISSUE THREAD

**Issue by djperrefort** [sncosmo/sncosmo#285]
It looks like `sncosmo.flatten_result` is looking for a dictionary entry that was removed in an earlier package version. Code to reproduce:

```ptyhon
>>> import sncosmo
>>> 
>>> data = sncosmo.load_example_data()
>>> model = sncosmo.Model(source='salt2')
>>> result, fitted_model = sncosmo.fit_lc(
>>>     data, model,
>>>     ['z', 't0', 'x0', 'x1', 'c'],  # parameters of model to vary
>>>     bounds={'z': (0.3, 0.7)})  # bounds on parameters (if any)
>>> 
>>> sncosmo.flatten_result(result)

Traceback (most recent call last):
  File "sncosmo/utils.py", line 107, in __getitem__
    return dict.__getitem__(self, name)
KeyError: 'cov_names'
```

**Comment by kboone** [comment]
Looks like `cov_names` was replaced by `vparam_names` in an older version of `sncosmo`, but this instance wasn't updated. Fixed in #288

**Comment by rbiswas4** [comment]
@kboone @djperrefort Can we then close this?

**Comment by kboone** [comment]
I was giving people a couple days to check out my PRs if they had any comments, but yes once that PR is merged this should be closed
