### ISSUE TITLE
sncosmo.get_ebv_from_map opening fits file

### ISSUE THREAD

**Issue by AlexGKim** [sncosmo/sncosmo#29]
I have a case that makes many calls to sncosmo.get_ebv_from_map.  For each call the dust map fits files are being opened.  I request new functionality for internal caching the maps for reuse on subsequent calls or allows the user to manage the maps by hand.

**Comment by kbarbary** [comment]
I've implemented an `SFD98Map` class that should address this issue. Comments welcome.

http://sncosmo.readthedocs.org/en/latest/api/sncosmo.SFD98Map.html
