### ISSUE TITLE
'Error' message in pip install, though everything seems to work.

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#290]
I tried doing ```pip install sncosmo``` in a new environment and got the following message:

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

astrotools 1.4.5 requires healpy, which is not installed.
astrotools 1.4.5 requires matplotlib, which is not installed.
```

However, `sncosmo` seemed to work.

**Comment by kboone** [comment]
This looks like something that is unrelated to sncosmo to me. If you try to install a different package do you get the same message? I don't think that astrotools is a dependency of sncosmo...

**Comment by rbiswas4** [comment]
Yes, I originally thought it might be an astropy thing, but you are right ... it could be related to my setup as well. Will check.

**Comment by benjaminrose** [comment]
@rbiswas4, are you still getting this error, or should we close this issue?
