### ISSUE TITLE
iminuit integration broken with iminuit==2.0.0

### ISSUE THREAD

**Issue by kosiokarchev** [sncosmo/sncosmo#291]
Hello,
A few days ago the `iminuit` package was updated to version 2.0.0, and now it seems that the integration with the `fit_lc` function is broken:
```
>>> import sncosmo
>>> data = sncosmo.load_example_data()
>>> model = sncosmo.Model(source='SALT2')
>>> sncosmo.fit_lc(data, model, ('t0',))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/sncosmo/fitting.py", line 670, in fit_lc
    m = iminuit.Minuit(fitchisq, errordef=1.,
  File "/usr/lib/python3.9/site-packages/iminuit/_minuit.py", line 485, in __init__
    self._init_state = _make_init_state(self._pos2var, args, kwds)
  File "/usr/lib/python3.9/site-packages/iminuit/_minuit.py", line 1401, in _make_init_state
    raise RuntimeError(
RuntimeError: errordef is not one of the parameters []
```
This works when `iminuit` is downgraded to 1.5.4 (the latest 1.x version).

PS Thanks for your work on the package, it's a huge relief for someone just getting into the field!

**Comment by kboone** [comment]
It looks like the entire API was reworked in the latest version of `iminuit`. The changes are listed here: https://iminuit.readthedocs.io/en/stable/changelog.html

There will need to be some significant changes in `sncosmo` to get things working with `iminuit` 2.0. For now, I would recommend sticking with `iminuit` v1.5.4.

@kbarbary, how do you feel about this? With all of the changes, we'll need to rewrite a good chunk of `fit_lc`. It looks like that should be pretty straightforward, but it won't be easy to maintain compatibility with both `iminuit` v1.x and v2.x. We probably need to pick one of the two going forward...

**Comment by kboone** [comment]
I updated `sncosmo` to use the new `iminuit` API in #292, so checkout that branch if you want to use `sncosmo` with `iminuit>=2.0`.

**Comment by kboone** [comment]
#292 has been merged, so this is fixed in the `master` branch now.
