### ISSUE TITLE
Travis CI changes

### ISSUE THREAD

**Issue by kboone** [sncosmo/sncosmo#293]
Travis CI is shutting down travis-ci.org (which is what `sncosmo` uses for CI) in a couple weeks. Per their blog, it looks like they will move everybody to a "trial" plan with a limited number of credits:

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

In the short term, I think that we just need to switch the domain in the `sncosmo` code from travis-ci.org to travis-ci.com. However, we will likely use up all of the credits after not too long and have to either pay or switch to a different CI tool.

On the zoom chat a few weeks ago we talked about switching to github actions. That is probably the easiest solution here.

**Comment by ykwang1** [comment]
Hey @kboone, we're currently going over testing and CI in Brigitta's astr597 class, and I think I could probably help with the migration to github actions. If that works for you, I can start looking at it mid next week and probably open a PR in class next Friday.

**Comment by kboone** [comment]
That would be great! As a first pass, I think that we are looking to setup github actions that do everything that the Travis build currently does. You can see the setup for that [here](https://github.com/sncosmo/sncosmo/blob/master/.travis.yml). That involves:
- Running the tests (`pytest`)
- Running the style check (`./checkstyle`)
- Running a coverage test (`pytest --cov=sncosmo`)
- Testing the doc build (`make html` in the docs directory).

You can see the commands that do all of this for the current Travis setup [here](https://github.com/sncosmo/sncosmo/blob/master/.travis.yml)

It would be nice to also automate pypi deployment. That isn't something that we currently do.

**Comment by djperrefort** [comment]
GHA also opens up possibilities for CDE and doc testing that could be useful for saving us time and promoting continued stability in the long run. 

I'm a big supporter of switching platforms.

**Comment by kbarbary** [comment]
We switched to github actions for SEP and I am a big fan. Makes the release procedure trivial and allows us to build wheels for all platforms:
https://github.com/kbarbary/sep/tree/master/.github/workflows

**Comment by bsipocz** [comment]
> It would be nice to also automate pypi deployment. That isn't something that we currently do.

Automating deployment is also on my list for astroquery (we used to have CD with travis, but I haven't yet migrated that part to GHA). 
We may not get to the weeds of wheels/etc for non pure python libs during class, but if we do I'll add sncosmo for our list. I suppose you would trigger the wheel building and pypi publishing with release tagging? Do you currently build wheels for it?

(FYI another example for a much simpler case is here for pytest-doctestplus: https://github.com/astropy/pytest-doctestplus/blob/master/.github/workflows/publish.yml)

**Comment by kboone** [comment]
I think that getting testing working on GHA is the top priority.

We don't currently build wheels for `sncosmo`, and the releases are all done manually. It looks like @kbarbary has a workflow for building wheels for `sep` in the link that he sent previously. I believe that `sep` and `sncosmo` have very similar package architectures (with lots of cython code), so that workflow will likely work for `sncosmo` with minimal changes.

**Comment by djperrefort** [comment]
It's worth mentioning that GitHub provides a prebuilt workflow template for deploying PyPi packages. By default, the workflow is triggered every time a release is generated on the repository ([link](https://github.com/actions/starter-workflows/blob/c59b62dee0eae1f9f368b7011cf05c2fc42cf084/ci/python-publish.yml)). The example is a little simpler than what astropy uses, particularly since it's not clear to me that we need to build the test suite as part of the CDE procedure (under the assumption that we wouldn't deploy without first checking the tests anyways).

Triggering on a release is probably best suited here, with dedicated, separate actions for testing the code/docs. Although, as @kboone said, this should come second to the test suite.

**Comment by bsipocz** [comment]
> me that we need to build the test suite as part of the CDE procedure (under the assumption that we wouldn't deploy without first checking the tests anyways

In my experience, it's a very good practice to tie the deployment to passing test status, there can be last-minute hick-ups as well as assumptions are not always followed for various reasons. 

(And I'm not at all advocating to use the astropy wheel solution here. While the azure templating we currently use is very powerful, it predates the mass switch to GHA and was mostly driven (and now being kept in place) by the desire to have one central template for multiple projects within openastronomy (astropy, sunpy, poliastro, etc). I would say it's not unrealistic to expect astropy to switch it all to GHA,  but currently, a few of us on the infra team cannot spend as much time on it as we used to, so pragmatically  a "don't fix what's not broken" approach is preferred for us, while here you would be better off not buying in multiple CI platforms, especially if they are of the same owner as it's the case for pipelines and GHA.)

**Comment by kboone** [comment]
Travis CI is officially down now, so our CI is no longer running. I'm going to work on finishing the transition to Github actions.

**Comment by bsipocz** [comment]
@kboone - I suppose this can be closed now.
