### ISSUE TITLE
Docs page "List of Built-in Sources" is blank

### ISSUE THREAD

**Issue by benjaminrose** [sncosmo/sncosmo#295]
I don't think the HTML page should be blank, https://sncosmo.readthedocs.io/en/stable/source-list.html. It looks like the docs page, https://github.com/sncosmo/sncosmo/blob/master/docs/source-list.rst, is not blank.

Does anyone know what is happening?

**Comment by kboone** [comment]
Some of the new models that we added had invalid formatting that broke the parser. Fixed in #298
