### ISSUE TITLE
SNEMO model not fully documented

### ISSUE THREAD

**Issue by benjaminrose** [sncosmo/sncosmo#299]
Several things:
- [x] No API documentation, unlike [SALT2](https://sncosmo.readthedocs.io/en/stable/api/sncosmo.SALT2Source.html)
- [x] Not apart of [Class Inheritance Diagram](https://sncosmo.readthedocs.io/en/stable/reference.html#class-inheritance-diagrams)

These issues are also present for other models. The source list is huge, so we likely don't want to add every model/source. Do we have an expectation for what should be a part of the API and class inheritance documentation?

Maybe we need to write a tutorial on how to add a new source, containing a checklist for PR reviews?

**Comment by kbarbary** [comment]
While the list of built in sources is long, the number of unique _classes_ isn't that long: most of the sources are `TimeSeriesSource` instances and therefore all have the same API.

`SNEMO` should have been added to the docs when the class was added to sncosmo: that was an oversight! I believe fixing this is a two line change to https://github.com/sncosmo/sncosmo/blob/master/docs/reference.rst: add `SNEMO` to the list under "source components of model" and to the inheritance diagrams at the bottom of the page.

**Comment by benjaminrose** [comment]
Thanks. #312 fixed this issue.
