### ISSUE TITLE
should result of `nest_lc()` and `fit_lc()` be more consistent?

### ISSUE THREAD

**Issue by kbarbary** [sncosmo/sncosmo#30]
`nest_lc` and `fit_lc` both return result dictionaries with a lot of similar fields (e.g. `param_names`, `errors`, `covariance`). However, there are some inconsistencies:

* In `fit_lc()`, `param_names` contains all parameters of the model, while in `nest_lc()` it only contains the *varied* parameters. (In `fit_lc()`, `cov_names` is used to denote the varied parameters.)

* `fit_lc()` has a `parameters` array with all the parameters, while `nest_lc()` has a `param_dict` dictionary with all the parameters.

This inconsistency arises because the primary quantity of interest returned by `nest_lc()` is the `samples` array, and `param_names` indicates what the columns of that array are. It seems natural that `samples` only contains varied parameters.

**Comment by kbarbary** [comment]
I've backtracked a bit on this. In order to keep backwards compatibility, we can't have `nest_lc` only return samples. However, I've done as much as I think possible to make the results consistent.

Here's a list of the consistent fields now:

- `parameters`: 1-d array of all parameter values, including fixed ones.
- `vparam_names`: names of only varied parameters
- `covariance`: 2-d array of covariance for only varied parameters
- `errors`: OrderedDict of errors (just varied parameters)
- `ncall`
- `ndof`

The results of `fit_lc` also include `param_names` (list of all parameters, corresponding to `model.param_names`) whereas `nest_lc` does not. I would add it to `nest_lc`, but it would break backwards compatibility, since this field formerly was used for the varied parameter names.

**Comment by rbiswas4** [comment]
I may be forgetting part of our discussion, but the motivation for consistency was to have a uniform set of operations to obtain the most commonly used results ie. summary statistics.

So, can we tackle this by leaving nest_lc and fit_lc alone as you suggest, but add a wrapper function:: 
    
    results0 = nest_lc(...)
    results1 = fit_lc(...)
 
where results0 and results1 are not completely consistent, but a wrapper function gives consistent results
    get_summarystats(results0)
    get_summarystats(results1)  

In fact, I think we could do this by not actually including the wrapper function in the code (one person 
will want to use mean(samples), another will want median(samples), etc.) but provide an example in the documentation.

**Comment by kbarbary** [comment]
The results are now almost entirely consistent, so I don't really see the benefit of a function like `get_summarystats`.

We had discussed not having `nest_lc` calculate any sort of mean parameters. However, the return value is currently `res, est_model` where the latter is a copy of the model *with the parameters set to mean values*. Unless we get rid of this second return value (backwards incompatible!) there's really no point to getting rid of the summary stats in `res`.
