### ISSUE TITLE
Dropping bands from data: band out of model wavelenght range

### ISSUE THREAD

**Issue by fraancha** [sncosmo/sncosmo#301]
Hello!
When I fit a SALT2 model in version 2.4 to simulated SNANA data from the same model, I get the warning that one band is outside the model wavelength.
However, the model's wavelength range is 2000-9200 and the wavelength range of the g-band that has that problem is 3920-5630. I also tried it with the ZTF and SDSS g-bands, getting the same warning.
I also divided the lowest band wavelength by one plus the maximum redshift fitted and the result is 2410.67 which is also within the model range.

I would be very grateful if you could please help me with this.
Thank you very much in advance!

**Comment by kboone** [comment]
Hmm, strange. Somehow your model redshift must be getting set to a value that redshifts the model outside of the bandpass. Are you letting the redshift be a free parameter in your fit? Can you provide some code to reproduce this problem?

**Comment by fraancha** [comment]
Yes, that's what it was! and now it is fixed
the setting had a redshift limit but the upper bound was out of the wavelength range of the model.
Thank you very much!
