### ISSUE TITLE
SNCosmo installs a "tests" package

### ISSUE THREAD

**Issue by kboone** [sncosmo/sncosmo#308]
The `sncosmo.tests` package gets installed as `tests`, so that when you do `import tests` it gets imported. I don't think that this behavior was intended, and it should probably only get imported as `import sncosmo.tests`.

**Comment by kbarbary** [comment]
Yeah that was certainly not intended! I'm suprised that `packages=['sncosmo', 'sncosmo.tests']` in `setup()` results in this behavior. Anyway, is this fixed now with #309?

**Comment by kboone** [comment]
Honestly, I'm not really sure how this happened. I tested it with a fresh install with #309 and it didn't happen, so it looks like it is fixed now.
