### ISSUE TITLE
Add function chisq to fit_lc() arguments

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#31]
It would be nice to be able to experiment with different Likelihood functions in fit_lc(). This could be done by extending the set of arguments to include a callable (perhaps with a defualt method) to use rather than the local fitchisq function defined within fit_lc() currently.

**Comment by kbarbary** [comment]
`fit_lc` is now sufficiently complicated that this doesn't make sense to have anymore: with model convariance, we are redefining the chisq function between each fit, so a single user-specified one doesn't make sense.
