### ISSUE TITLE
Update the version automatically with setuptools_scm

### ISSUE THREAD

**Issue by kboone** [sncosmo/sncosmo#311]
Currently, the version is hardcoded in `sncosmo`. This works ok, but requires the maintainers to manually update it for new releases, and means that it isn't possible to tell if a version of SNCosmo is from a release or from some development version.

Most of the core astropy packages have moved to using `setuptools_scm` to manage their version automatically. This pulls the version directly from git tags, and includes a reference to the latest git commit into the version tag for development versions. This could be useful for debugging.

As part of #309, we considered moving to this package, but found that it has a few downsides.
- Source distributions that come from e.g. tarballs don't have git history information, so they can't be built. (does anybody even use these?) The source distributions on PyPI are still fine since they are generated with the release info.
- `python setup.py install` then requires that `setuptools_scm` is installed locally. This is a deprecated way of installing packages anyway, and the modern `pip install` works as expected.
- The version can be detected in an installed package automatically using `importlib.metadata` but only on Python 3.8+. A workaround is needed for Python 3.6/3.7 that we currently support.

Ultimately, while it would be nice to have better version tracking, it adds a bunch of tradeoffs for legacy support that I don't think are worth it at this time.

If we decide that we want to add this support, the code for it can be found by undoing 9564c5f36e25a20ec10a872b3d15432a2e2c093e.

**Comment by kboone** [comment]
I don't think that we want to go ahead with this at this time, so I'm going to close this.

**Comment by kbarbary** [comment]
This all makes sense. Might be good to revisit later. My take on automatic versioning like this was originally that it wasn't worth the added workflow complexity to save a few manual steps for a maintainer. However, with pyproject.toml / modern pip, the added complexity is probably better abstracted than it was back then.

> means that it isn't possible to tell if a version of SNCosmo is from a release or from some development version.

For now the maintainer can bump the version to `vX.Y.dev` after release. I used to do that but got lazy about it at some point.

**Comment by kboone** [comment]
From my playing around with this, the new tools like `setuptools_scm` all work really well if you are on Python 3.8+ and using modern build tools. However, if you want to support older python versions or older build methods then things get a bit messy. I think that it is easiest for now to keep things as is, but maybe revisit it in a year or two.
