### ISSUE TITLE
Improve cross-compatibility between SNANA and SNCosmo

### ISSUE THREAD

**Issue by benjaminrose** [sncosmo/sncosmo#318]
I am working on fitting SNANA sims with SNIa models in SNCosmo. As a result, I am finding some unnecessary name conversions between the two programs. 

Between my `read_snana_fits()` and `mcmc_lc()` calls, I currently need to 
```python
data.rename_column("FLUXCAL", "flux")
data.rename_column("FLUXCALERR", "fluxerr")
data.rename_column("ZEROPT", "zp")
```

We can improve this workflow by either

1. adding these names to [`PHOTDATA_ALIASES`](https://github.com/sncosmo/sncosmo/blob/750865e13661f54b8e20b778e76b46b3f43a7561/sncosmo/photdata.py#L16)
2. or, adding an extra flag to `read_snana_fits()` that performs some standardization on names. 

I think option 1 is best, but option 2 could also add a `data["zpsys"] = "ab"` column if no zero-point system is found.

**Comment by kboone** [comment]
The first option sounds good to me. Want to write up a quick PR and we can get it into v2.6?

Is the zeropoint in SNANA standardized internally, or are there models with a range of different zeropoints? We need to be very careful about assuming a zeropoint/zpsystem when one isn't specified.

**Comment by benjaminrose** [comment]
I might be able to get a PR in, when are you releasing v2.6?

I am not sure if SNANA has a standard, but we can add an option where the user can provide the string that gets assigned to `data["zpsys"]`, but at that point it is probably better to just have the user specifically add the column after import.

**Comment by kboone** [comment]
I'm hoping to release 2.6 today or tomorrow.

This change is just adding a couple of strings to a list. I can whip it up
in a couple mins if you want.

**Comment by benjaminrose** [comment]
I'm working on it now. I just needed to finish another project first (and before the end of the day).

**Comment by benjaminrose** [comment]
I am double-checking that `FLUXCAL` is what I think it is. In doing this, I found out that SNANA uses both `FLUX` and `FLUXCAL`. If a user imports a SNANA data file that has both, option 1 will cause a problem and break previously working scripts.

**Comment by kboone** [comment]
Reading the SNANA manual, it looks to me like the `FLUX` column is the flux in ADU with the zeropoint given by `ZEROPT` while `FLUXCAL` is the flux scaled by 10^11 (a zeropoint of 27.5). So `FLUXCAL` is probably something that we need to handle separately.

Adding `zeropt` to the list of aliases in photdata seems to make sense though, and would probably make most things work.

**Comment by kboone** [comment]
Now I'm confused... it looks like only `FLUXCAL` and `FLUXCALERR` are available in most files, and that they should have a zeropoint of 27.5?

Let's hold off on this for the v2.6.0 release and take some time to figure it out. I looked at some of my scripts for reading SNANA light curves and they are a mess...

**Comment by rbiswas4** [comment]
> it looks like only FLUXCAL and FLUXCALERR are available in most files, and that they should have a zeropoint of 27.5

This is correct. There is an additional difference in the definition of `x_0/m_B` 

I can take a look at this PR, but it won't happen by tomorrow. So please hold off on it for the 2.6.0 release.  Also, for compatibility, I think the simlib_read function is out of date.  There is an issue on this already. 
For more cross-compatiblity an item that would help is casting SNCosmo in SNANA form to enable running the SNANA fitter.

**Comment by kboone** [comment]
While we are talking about SNCosmo/SNANA integration problems here one thing that bothers me is that the table name must be manually specified when reading an SNANA ascii file. This is documented in the docstring of `read_snana_ascii`, but is really annoying and there is probably a better solution. It would be good to look into how SNANA handles this and copy it.

**Comment by benjaminrose** [comment]
Sounds like we need a meta/tracking issue. Is this that issue or is this issue just about the PHOTODATA_ALIASES?
