### ISSUE TITLE
Redundant check-all-builtins script

### ISSUE THREAD

**Issue by kboone** [sncosmo/sncosmo#332]
I didn't realize that there was already a `check-all-builtins` script when I wrote the `tox -e builtins` tests. Both are very similar, but I like the tox approach better because it will check all of the builtins and tell you exactly which ones failed rather than failing at the first error.

I propose that we just remove the `check-all-builtins` script.

**Comment by benjaminrose** [comment]
A few questions to think about as we consider this: Is there any automated system that uses the `check-all-builtins` script? Is this script referenced in the docs anywhere?

**Comment by kbarbary** [comment]
> Is there any automated system that uses the check-all-builtins script? Is this script referenced in the docs anywhere?

There shouldn't be any dependencies or references to it. I wrote this script as a quick check to be run occasionally by a maintainer -- I wanted to be a little more proactive about discovering broken links before they were reported, but wasn't sure if this sort of thing would be good to fully automate, since it downloads (I think) several GB of data, and would have required some work setting up a cron job in CI.

All that is to say, I think it is fine to remove it in favor of something better.

**Comment by kboone** [comment]
There were a few broken path issues that popped up with the builtins a while back. I wasn't aware of your script, so I implemented basically the same thing in a pytest module that can be run with `tox -e builtins`.

It downloads ~1 GB of data and runs in a few minutes on the GitHub Actions CI. That isn't too much of a burden, so for now I made it just run whenever the tests run as a separate action. It would make sense to set it up as a cron job to do a ~weekly test for broken links.

**Comment by benjaminrose** [comment]
I’ve set up cron jobs with GitHub actions before, if we want, I can do that here.

**Comment by kboone** [comment]
I think that running `tox -e builtins` on something like a weekly schedule would probably be good if you want to set that up.

**Comment by benjaminrose** [comment]
Cron job is added and [looks good](https://github.com/sncosmo/sncosmo/actions/runs/1425902808). It can even be [run manually](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/).

**Comment by kboone** [comment]
Looks good. If the builtins get too large in the future we might want to remove the check on all commits to master, but for now might as well run it every time. I'm going to remove the `check-all-builtins` script.
