### ISSUE TITLE
Support pandas dataframe

### ISSUE THREAD

**Issue by MickaelRigault** [sncosmo/sncosmo#349]
Hello guys, 

Simple question: is there a plan to support pandas DataFrame in addition to astropy table for the LC data ? 
(in realize_lc() and fit_lc() for instance).

Cheers

**Comment by benjaminrose** [comment]
There is no current plan for this. Would this include switching the default object that is returned from functions? With the increased popularity and usefulness of DataFrames, I do think we should discuss how they should interact with SNCosmo, but I think this would be better as a discussion or a more formal [EPS](https://github.com/sncosmo/sncosmo-eps).

**Comment by kboone** [comment]
Astropy has functions to convert pandas dataframes to/from astropy tables, see https://docs.astropy.org/en/stable/table/pandas.html

I don't think that this is something that sncosmo needs to explicitly support.

**Comment by MickaelRigault** [comment]
Ok. this is indeed what I am using, but it creates overhead in the code.
That is small though. I also created small tools for the Result object
(like to_pandas()).
I was wondering if you wanted them in sncosmo.
