### ISSUE TITLE
SNCosmo Python Version Support

### ISSUE THREAD

**Issue by benjaminrose** [sncosmo/sncosmo#353]
Right now, SNCosmo's Python version support is a bit unclear. In the `setup.cfg` we state [`>=3.5`](python_requires = >=3.5) and this is what PyPi quotes. However, the [documentation states >3.4.](https://sncosmo.readthedocs.io/en/stable/install.html) And we do not currently test on 3.4, 3.5, 3.10, or 3.11 all available (-ish) versions of python. We should make this consistent.

## Additional pieces of information.

- The `tox.ini` file only has environments for `{36,37,38,39}`.
- Python 3.5 and 3.6 are no longer supported versions of Python. And the PSF is only doing security updates for versions 3.7, 3.8, and 3.9. These will no longer receive updates in June 2023, October 2024, and October 2025 respectively.
- Conda-forge seems to be only [building SNCosmo for 3.7-3.10.](https://anaconda.org/conda-forge/sncosmo/files?sort=basename&sort_order=desc) I assume that 3.11 is only missing because it was released 2022-10-24.
- I did not check what Python versions are supported with our dependencies.

## Possible action items

- [x] Update documentation to match `setup.cfg`.
- [x] Update `setup.cfg`, to >=3.6, to match tests/conda-forge.
- [ ] Leave it as is, so we don't break anything.
- [ ] Add some clarifying text to the documentation explaining what we are doing.
    - [x] Add a section to the contributing documentation indicating how to change the supported Python version. Aka listing all the files that have hard coded python versions, to try to keep things from getting out of sync again. Currently, I think this is `tox.ini`, `.github/workflows/run_tests.yml`, `setup.cfg`, & `docs/install.rst`.
- [x] Update one test to always test latest version by using `python: 3.x` notation.
    - May also require updates to `tox.ini`.
- [x] Add a basic (aka shorter) test set that we can run on all supported versions of Python. Something like `toxenv: py39` may be sufficient.
    - May also require updates to `tox.ini`.
- [x] Add one or both, [`schedule` or `workflow_dispatch`](https://github.com/sncosmo/sncosmo/blob/a18a8e5459c1593ed2ac49e761b9ca616c9d5bd6/.github/workflows/verify_builtins_downloads.yml#L7), to [`run_tests.yml`](https://github.com/sncosmo/sncosmo/blob/a18a8e5459c1593ed2ac49e761b9ca616c9d5bd6/.github/workflows/run_tests.yml) allowing for future tests with updated external dependencies but no updates to the code (aka new Python versions).
- [ ] I think it would be nice to also test (with an "ok to fail" flag) using beta releases of python, just to know a new version of python does not break our code.

**Comment by benjaminrose** [comment]
Looking at https://pypistats.org/packages/sncosmo, it seems like SNCosmo is not used with python 3.4 or 3.5 and very rarely used with python 3.6 or 3.7. It seems like mostly it is used with 3.8, with some usage with 3.9, 3.10, and Null.

I think we can update the documentation and likely also drop python 3.5 in `setup.cfg`. This would make everything match the current test suite. We should probably add 3.10 and 3.11 tests.

**Comment by benjaminrose** [comment]
It looks like we are no longer able to test with python 3.6, https://github.com/sncosmo/sncosmo/actions/runs/4367353719/jobs/7723095201

**Comment by kboone** [comment]
Let's drop support for Python 3.6. It hit EOL in December 2021 and should no longer be used.
