### ISSUE TITLE
Two JWST MIRI Filters are swapped

### ISSUE THREAD

**Issue by jpierel14** [sncosmo/sncosmo#356]
I've found that the F1130W and F1280W filters have been swapped which is...not great for anyone doing synthetic photometry or light curve fitting with MIRI (and note proposals are due next week).
<img width="515" alt="Screen Shot 2023-01-19 at 12 07 46 PM" src="https://user-images.githubusercontent.com/22748184/213519120-a88c07b3-8c1d-4493-9b65-08944478605a.png">

**Comment by benjaminrose** [comment]
@jpierel14 do all the others look good?

**Comment by jpierel14** [comment]
Yeah I'm pretty sure the filenames just need to be swapped they look correct otherwise

**Comment by benjaminrose** [comment]
Yeah, the bug is here: https://gist.github.com/kbarbary/966bd8fcfa42e3631b6a1b8ae0a4c882#file-split_jwst_miri_bands-py-L8. It was when creating the files, some 6 years ago.

**Comment by jpierel14** [comment]
Okay well let's definitely get this fixed and then in general I can check to see if these should all be updated.

**Comment by jpierel14** [comment]
Awesome thanks @benjaminrose
