### ISSUE TITLE
Covariance in photometric data

### ISSUE THREAD

**Issue by kbarbary** [sncosmo/sncosmo#4]
There is currently no way to specify covariance between data points.

**Comment by AlexGKim** [comment]
We in DES are at the point of needing to include covariance in counts and also in the zeropoints.  You recognized that this is an open issue.  Have you thoughts on the design?

**Comment by rbiswas4** [comment]
If we are in the paradigm of 1 table per SN: Why not have two tables : the current photometric data tables, and a relative covariance table which is N X N. If each observation in the light curve table has an index, the covariance table inherits the index in both rows and columns. Dropping rows in the light curve data, corresponds to removing the rows and columns corresponding to the index in the covariance table. I don't know how to do this is astropy.tables but it is easy to do in pandas. 

I think it becomes ugly when one wants to move from the 1 table per SN paradigm to 1 table for a large number of SN.

@AlexGKim Out of curiosity: What drives the covariance of counts from independent realizations of sky noise sampled by the observations? This would mean that there is some unconsidered variable (maybe instrumental/camera) which does not change independently from observation to observation. Is hiding this through a photometry covariance an intermediate step or one of convenience?

**Comment by AlexGKim** [comment]
Photometric extractions of multi-epoch data have covariance because of the common host galaxy background and astrometric position.

Is it problematic for sncosmo fitters to SALT fit an entire SN dataset simultaneously?  If so, perhaps DES should be looking at a HMC solution rather than sncosmo.

**Comment by rbiswas4** [comment]
> Photometric extractions of multi-epoch data have covariance because of the common host galaxy background and astrometric position.

Thanks!

> Is it problematic for sncosmo fitters to SALT fit an entire SN dataset simultaneously? If so, perhaps DES should be looking at a HMC solution rather than sncosmo.

Do you mean a solution over the entire dataset of many SN where the fits are not independent for each SN?

**Comment by kbarbary** [comment]
Closed by #168 (though using covariance in fit_lc is still to-be-done)
