### ISSUE TITLE
Model and spectra data hosting/fallbacks

### ISSUE THREAD

**Issue by kbarbary** [sncosmo/sncosmo#5]
Currently, data for "built-in" models and spectra are hosted in a
variety of places (the original provider's origin, if possible).

* It would be ideal to have a central place to host the data 
  (data.astropy.org/ perhaps)

* There should be a local fallback option.

**Comment by kbarbary** [comment]
@rcthomas Do you know the best way to do a redirect for a data file URL? For example, we want to have sncosmo download a file at `http://sncosmo.github.io/data/models/` that redirects to the true location, such as `http://supernovae.in2p3.fr/salt/lib/exe/fetch.php?media=salt2_model_data-2-4.tar.gz`. We obviously don't control the HTTP server at github.io, so it seems like an HTTP redirect is not possible. I'm guessing an HTML redirect in `<meta>` will only be respected by a web browser, not urllib2.

I guess we could do a "poor-man's" redirect where we get a file on `github.io` that simply contains the true URL as a string, and then explicitly get that URL.

The purpose of this is to avoid having to release a new version of the code when someone moves a data file.

cc @srodney

**Comment by srodney** [comment]
Directory redirects on github pages are pretty easy with Jekyll.   In my fork of sncosmo.github.io I've tested out redirects using https://github.com/jekyll/jekyll-redirect-from (which can also easily do a "redirect to").   See  My problem was on the other end :  I was redirecting to Dropbox, but I found that I would have to make a separate link for each and every file, instead of just a directory link.

**Comment by kbarbary** [comment]
Did that actually work with sncosmo to get a model? The jekyll redirects produce an HTML page with the redirect in the `<meta>` tag. While this works for a web browser (designed to read HTML content), I was worried that it wouldn't work for urllib2, which is designed to get arbitrary resources and might not even look at the HTML content of the resource it fetched. (urllib2 is what's used to actually download the data in astropy's data download utilities.) But perhaps my fears were misplaced?

**Comment by srodney** [comment]
No.  You're right.  urllib2 doesn't handle the meta redirect.    There's the option of parsing the html:

http://stackoverflow.com/questions/2318446/how-to-follow-meta-refreshes-in-python

**Comment by rcthomas** [comment]
If there is no way to get an actual redirect at HTTP level, you have to
delegate it to application level.  This doesn't have to be a bad thing.

Rollin


On Thu, Jan 15, 2015 at 8:18 PM, Steve Rodney <notifications@github.com>
wrote:

> No. You're right. urllib2 doesn't handle the meta redirect. There's the
> option of parsing the html:
>
>
> http://stackoverflow.com/questions/2318446/how-to-follow-meta-refreshes-in-python
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sncosmo/sncosmo/issues/5#issuecomment-70206407>.
>



-- 
Dr. R. C. Thomas
Computational Cosmology Center
Lawrence Berkeley National Lab
1 Cyclotron Road Mail Stop 50B4206
Berkeley, California 94720-8151
510.486.4697

**Comment by kbarbary** [comment]
@rcthomas OK thanks for the confirmation. My new idea is to store redirects in a single JSON file and have sncosmo always look at that (see comment in sncosmo/sncosmo.github.io#1).

**Comment by kbarbary** [comment]
Closed by #73
