### ISSUE TITLE
TwoStretchSource

### ISSUE THREAD

**Issue by kbarbary** [sncosmo/sncosmo#66]
Just discussed with @drhay53 about adding the "two stretch model". It would be really similar to the implementation of `StretchSource`, but with an extra stretch parameter. Something like:

``` python
class TwoStretchSource(Source):
    _param_names = ['amplitude', 's1', 's2']  # extra stretch parameter
    param_names_latex = ['A', 's_1', 's_2']

    def __init__(self, phase, wave, flux, name=None, version=None):
        self.name = name
        self.version = version
        self._phase = phase
        self._wave = wave
        self._parameters = np.array([1., 1., 1.])  # initialize both stretches to 1.
        self._model_flux = Spline2d(phase, wave, flux, kx=2, ky=2)

    def minphase(self):
        return self._parameters[1] * self._phase[0]  # minphase uses first stretch

    def maxphase(self):
        return self._parameters[2] * self._phase[-1]  # max phase uses second stretch

    def _flux(self, phase, wave):
        # for phases less than 0, adjust by first stretch.
        # for phases greater than 0, adjust by second stretch.
        mphase = np.where(phase < 0.,
                          phase / self._parameters[1],
                          phase / self._parameters[2])
        return self._parameters[0] * self._model_flux(mphase, wave)
```

**Comment by drhay53** [comment]
What is the proper github-y way for me to test this? Fork SNCosmo, add this to the source code, test it out, and do a pull-request?

**Comment by rbiswas4** [comment]
I am a little confused. I thought the stretch relates the time - peak to phase through:
(time - peak) =stretch* phase and this would be generalized to two equations depending on whether phase was positive or negative. But _flux for a particular phase would not depend on these stretch parameters. Similarly I would have expected minphase and maxphase to be independent of the stretch parameters. 

Maybe this is a very different kind of model ?

**Comment by kbarbary** [comment]
@drhay53 You need not modify the sncosmo source to use this. You can just plop it in a file `mymod.py`:

```python
import numpy as np
import sncosmo
from scipy.interpolate import RectBivariateSpline as Spline2d

class TwoStretchSource(sncosmo.Source):
    #
    # see source above
    #

# create a model using the source you just defined
source = TwoStretchSource(phase, wave, flux)  # need to get the phase, wave, flux grid separately
model = sncosmo.Model(source=source)
# fit the model or whatever...

```

**Comment by kbarbary** [comment]
@rbiswas4 There are two separate "phases" here. `self._phase` contains the phases corresponding to stretch of 1. The phase input to the `_flux` method is the actual observed "time - peaktime" in the SN restframe. The two are related via `phase = self._phase * s`.

**Comment by drhay53** [comment]
@kbarbary is there no way to access the default phase and wavelength of a built-in sncosmo.Model? For testing, I would want to just load the hsiao template and use whatever is there as the template for TwoStretchSource.

**Comment by kbarbary** [comment]
Unfortunately, there's no good way that's well documented!

Here's a hack:

```python
from sncosmo.builtins import get_url
from astropy.utils.data import download_file

remote_url = get_url('hsiao', version='3.0')
fn = download_file(remote_url, cache=True)
phase, wave, flux = sncosmo.read_griddata_fits(fn)
```

This depends on a very recent change so be sure you're working with current sncosmo master.

**Comment by rbiswas4** [comment]
I thought _phase, _wave accessed the native values that were read in ... is
that changed?

**Comment by kbarbary** [comment]
@rbiswas4 Yes, it's true that you can get the phase and wavelength grids by doing, e.g.,

```python
source = sncosmo.get_source('hsiao')
phase, wave = source._phase, source._wave 
```
but even this is a hack because these attributes start with `_` and are therefore meant to be "private" variables (in the Python sense).

The flux grid on the other hand is not even saved directly; only the interpolation coefficients are saved (in the `source._model_flux` attribute). I suppose you could reconstruct the flux grid by doing
```python
flux = source.flux(source._phase, source._wave)
```

**Comment by drhay53** [comment]
@kbarbary is there a reason why phase and wave are not public? 

Or, going a different direction; could a source just learn it's phase/wave/flux directly from a model?

**Comment by kbarbary** [comment]
@drhay53 In fact, phase and wavelength used to be public in previous versions (v0.2 and before I think). The reasoning for making them private is that not all sources will _necessarily_ have a "native" grid of phases and wavelengths (though all currently implemented models do). For example, imagine some model based on gaussian processes. Therefore, none of the functions that interact with models (such as `fit_lc` or `plot_lc`) should assume that the model has a grid of phases and wavelengths.

You could also say that the model is a smooth spectral surface and the grid is irrelevant: The fact that the smooth surface is initialized by fitting B splines to a grid of points when you call `Source.__init__()` is an "implementation detail," as they say.

All that said, one could make public the grids for models that define them, being careful not to rely on the grids for anything that is supposed to work on any general model.

I think in your second question you're asking if you could initialize, for example a `TwoStretchSource` from an already-initialized `TimeSeriesSource`, such as:
```python
source1 = sncosmo.get_source('hsiao')
source2 = sncosmo.TwoStretchSource(source1)
```
I've thought about making this possible. My hesitation is that the Hsiao template (or any other simple spectral timeseries) could be used equally well in a `TimeSeriesSource`, a `StretchSource`, or a `TwoStretchSource`. Why should `get_source('hsiao')` return the first rather than the second or third? Perhaps we should make the initialization something like:
```python
source1 = sncosmo.TimeSeriesSource('hsiao')
source2 = sncosmo.TwoStretchSource('hsiao')
```
where passing in the string `'hsiao'` rather than `phase, wave, flux` means to load the phase, wave, flux from the Hsiao template. I kinda like that, but it makes initializing a `Model` in a single line harder.

**Comment by kbarbary** [comment]
Closing this as outside the scope of sncosmo for the time being.
