### ISSUE TITLE
Specify single color for plot_lc

### ISSUE THREAD

**Issue by drhay53** [sncosmo/sncosmo#67]
It would be useful for the purposes of studying many light curve fits to be able to set the color of all of the plots to avoid straining to look at certain yellows and greens.

**Comment by kbarbary** [comment]
The color of each bandpass is determined based on its "central wavelength" via a single colormap that maps the range (3000 Angstroms, 10,000 Angstroms). Currently using [jet](https://twitter.com/michaelwaskom/status/512344441873367040) for that colormap. See here:

https://github.com/sncosmo/sncosmo/blob/master/sncosmo/plotting.py#L23

The quickest fix would be to simply use a better colormap. Want to change the colormap around and see what looks good? The next quickest fix would be to allow the user to specify the colormap and wavelength range instead of having them hard-coded. Yet more keyword args...

In general, I think `plot_lc()` could produce more aesthetically pleasing plots. We should get some serif fonts in there at least.

**Comment by kbarbary** [comment]
Actually now I see that you actually want no colormap at all, just a single color for all bandpasses. That could be accomplished with a keyword argument `color` that is either a single color *or* a colormap.

**Comment by drhay53** [comment]
I see that it would be easy in the source code to allow the colormap to be an option in plot_lc. What do you think is the best way to have all plots be the same color?

**Comment by kbarbary** [comment]
You probably have to check the class of the thing the user passes in. Do one thing if it is a `ColorMap`, otherwise treat it as a single color. I think there are some places in matplotlib where you can pass either a colormap or a single color. If so, I'd check to see how they handle things.

**Comment by drhay53** [comment]
As a user, I would probably be annoyed by having to retrieve the colormap from matplotlib myself. Could the user-input just be a string and then the code tries to retrieve a colormap, and falls back to just a single color if it doesn't exist? Then it would have to handle things if the user passed it some gibberish though (or a typo).

I dug around in the MPL source code for ~10 minutes and without knowing which methods allow the user to pass either/or, tracking it down quickly seems rather hopeless.

**Comment by kbarbary** [comment]
From a quick look at the docs, it seems like many methods allow a `cmap` argument or a `color` argument. For example:
http://matplotlib.org/api/pyplot_api.html?highlight=pyplot#matplotlib.pyplot.contour

`color` takes precedence, and if neither is specified, a default colormap is used. This seems like the way to go. I'll probably get to this eventually if you don't give it a go.

**Comment by drhay53** [comment]
Ah, but that example takes either a cmap or a color, through different arguments; I thought you meant we would pass either a cmap or a color through the same argument and handle it internally.

I may get to it this week sometime.

**Comment by kbarbary** [comment]
Yeah a single argument was my initial thought, but after seeing what mpl does, it's probably better to mirror it and use two separate arguments.

**Comment by kbarbary** [comment]
Example behavior in master:

```python
sncosmo.plot_lc(data, fitted_model, errors=res.errors, color='k', fname='test.png')
```

![test](https://cloud.githubusercontent.com/assets/970135/6240087/1675a8f6-b6bf-11e4-9180-0a85582bbc0e.png)

```python
cmap = cm.get_cmap('cool_r')
sncosmo.plot_lc(data, fitted_model, errors=res.errors, cmap=cmap, fname='test.png')
```

![test](https://cloud.githubusercontent.com/assets/970135/6240100/414ab44a-b6bf-11e4-9664-3a9cee8d69e1.png)
