### ISSUE TITLE
Can we get aliases of PhotData to work with ObsTable

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#70]
Currently, it is possible to have photometric data represented by `Tables` with column names representing the variables to be chosen from a list of aliases as explained in http://sncosmo.readthedocs.org/en/latest/photdata.html. Thus, column names such as `time` or `mid`, for example, are supposed to be equally well-recognized to be the time variable during plotting or fitting the data. However, this does not work for interpreting  sets of observations during simulations: http://sncosmo.readthedocs.org/en/latest/simulation.html, where the column name `time` cannot be replaced by `mjd`. While this problem can be averted by changing the column names of a set of observations (if they had a different name) using `astropy` method, it would be convenient if the same set of aliases worked on it

**Comment by kbarbary** [comment]
Closed by #167
