### ISSUE TITLE
sncosmo.Model(source='salt2') does not work without internet even if it is not the first time.

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#74]
My understanding of how the sncosmo.Model(source='salt2') was intended to work was:
1. SNCosmo downloads the source if it is not already cached
2. It caches it, so that on the next call, it would not be downloading it or requiring the internet.

I found that if I run this without internet having used this source before, I get the following error (but works fine if internet is available):

URLError                                  Traceback (most recent call last)
<ipython-input-2-21572f68193e> in <module>()
----> 1 model = sncosmo.Model(source='salt2-extended')

/Users/rbiswas/src/sncosmo/build/lib.macosx-10.5-x86_64-2.7/sncosmo/models.pyc in __init__(self, source, effects, effect_names, effect_frames)
    996         self.param_names_latex = ['z', 't_0']
    997         self._parameters = np.array([0., 0.])
--> 998         self._source = get_source(source, copy=True)
    999         self.description = None
   1000         self._effects = []

/Users/rbiswas/src/sncosmo/build/lib.macosx-10.5-x86_64-2.7/sncosmo/models.pyc in get_source(name, version, copy)
     86             return name
     87     else:
---> 88         return cp(registry.retrieve(Source, name, version=version))
     89
     90

/Users/rbiswas/src/sncosmo/build/lib.macosx-10.5-x86_64-2.7/sncosmo/registry.pyc in retrieve(data_class, name, version)
    194             regkey = (key[0], key[1], latest_version)
    195             func, args, meta = _loaders[regkey]
--> 196             _instances[regkey] = func(*args, name=name, version=latest_version)
    197             _instances[key] = _instances[regkey]
    198             return _instances[key]

/Users/rbiswas/src/sncosmo/build/lib.macosx-10.5-x86_64-2.7/sncosmo/builtins.pyc in load_salt2model(topdir, name, version)
     93
     94 def load_salt2model(topdir, name=None, version=None):
---> 95     remote_url = get_url(name, version)
     96     fn = download_file(remote_url, cache=True)
     97     t = tarfile.open(fn, 'r:gz')

/Users/rbiswas/src/sncosmo/build/lib.macosx-10.5-x86_64-2.7/sncosmo/builtins.pyc in get_url(name, version)
     39         from six.moves.urllib.request import urlopen
     40         import json
---> 41         f = urlopen("http://sncosmo.github.io/data/urls.json")
     42         urls = json.load(f)
     43         f.close()

/usr/local/manual/anaconda/python.app/Contents/lib/python2.7/urllib2.pyc in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    152     else:
    153         opener = _opener
--> 154     return opener.open(url, data, timeout)
    155
    156 def install_opener(opener):

/usr/local/manual/anaconda/python.app/Contents/lib/python2.7/urllib2.pyc in open(self, fullurl, data, timeout)
    429             req = meth(req)
    430
--> 431         response = self._open(req, data)
    432
    433         # post-process response

/usr/local/manual/anaconda/python.app/Contents/lib/python2.7/urllib2.pyc in _open(self, req, data)
    447         protocol = req.get_type()
    448         result = self._call_chain(self.handle_open, protocol, protocol +
--> 449                                   '_open', req)
    450         if result:
    451             return result

/usr/local/manual/anaconda/python.app/Contents/lib/python2.7/urllib2.pyc in _call_chain(self, chain, kind, meth_name, *args)
    407             func = getattr(handler, meth_name)
    408
--> 409             result = func(*args)
    410             if result is not None:
    411                 return result

/usr/local/manual/anaconda/python.app/Contents/lib/python2.7/urllib2.pyc in http_open(self, req)
   1225
   1226     def http_open(self, req):
-> 1227         return self.do_open(httplib.HTTPConnection, req)
   1228
   1229     http_request = AbstractHTTPHandler.do_request_

/usr/local/manual/anaconda/python.app/Contents/lib/python2.7/urllib2.pyc in do_open(self, http_class, req, **http_conn_args)
   1195         except socket.error, err: # XXX what error?
   1196             h.close()
-> 1197             raise URLError(err)
   1198         else:
   1199             try:

URLError: <urlopen error [Errno 8] nodename nor s

**Comment by kbarbary** [comment]
This is a known issue that will be fixed as soon as #73 is merged. And I'll probably do that today!

**Comment by kbarbary** [comment]
should be fixed.
