### ISSUE TITLE
nest_lc parameters being used internally in the wrong order

### ISSUE THREAD

**Issue by drhay53** [sncosmo/sncosmo#76]
This also applies to mcmc_lc. Somewhere internally, sncosmo is re-ordering the order of the parameters and not applying that to the plots or to the 'est_model'. So if the user puts the parameters in the wrong order when calling nest_lc or mcmc_lc, the returned model and parameters are incorrect. 

    # hacking the sncosmo internal grid for the model
    model = sncosmo.Model(source='hsiao')
    phase = np.linspace( -20,85, 106 )
    wave  = np.linspace( 1000,25000, 1501 )
    flux  = model.flux( phase, wave )
    
    # make the source, apply dust, set it to the right z
    source = sncosmo.StretchSource( phase,wave,flux )
    dust   = sncosmo.CCM89Dust()
    dust.set( r_v=2.8 )
    model  = sncosmo.Model(source=source, effects=[dust], effect_names=['host'], effect_frames=['rest'])
    model.set(z=z)
    res, fitted_model = sncosmo.nest_lc(data, model, 
            ['t0', 'amplitude', 's', 'hostebv'], 
            guess_amplitude_bound=True,
            bounds={'s':(0.5,2), 'hostebv':(-1,1)})

**Comment by kbarbary** [comment]
Should be fixed now. I didn't address `mcmc_lc()` though because the return value is about to change to match `fit_lc()` and `nest_lc()`.
