### ISSUE TITLE
Retrieving things from registry using subclass

### ISSUE THREAD

**Issue by AlexGKim** [sncosmo/sncosmo#90]
Is this proper behavior?  I can get this TimeSeriesSource only as a Source.

In [95]: sncosmo.registry.retrieve(sncosmo.Source,"nugent-sn1a", version='1.2')
Out[95]: <TimeSeriesSource 'nugent-sn1a' version='1.2' at 0x1059fcf90>

In [97]: sncosmo.registry.retrieve(sncosmo.TimeSeriesSource,"nugent-sn1a", version='1.2')
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-97-2a9a87d7d031> in <module>()
----> 1 sncosmo.registry.retrieve(sncosmo.TimeSeriesSource,"nugent-sn1a", version='1.2')

/Users/akim/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sncosmo-1.1.dev516-py2.7-macosx-10.6-x86_64.egg/sncosmo/registry.pyc in retrieve(data_class, name, version)
    208         raise Exception(
    209             "No {0} named {1!r} in registry. Registered names: '{2}'"
--> 210             .format(data_class.__name__, name, "', '".join(registered_names)))
    211 
    212     registered_versions = [regkey[2] for regkey in _loaders.keys()

Exception: No TimeSeriesSource named 'nugent-sn1a' in registry. Registered names: ''

**Comment by AlexGKim** [comment]
In [98]: sncosmo.registry.retrieve(sncosmo.Source,"nugent-sn1a", version='1.2')
Out[98]: <TimeSeriesSource 'nugent-sn1a' version='1.2' at 0x1059fcf90>

In [99]: sncosmo.registry.retrieve(sncosmo.TimeSeriesSource,"nugent-sn1a", version='1.2')
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-99-2a9a87d7d031> in <module>()
----> 1 sncosmo.registry.retrieve(sncosmo.TimeSeriesSource,"nugent-sn1a", version='1.2')

/Users/akim/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sncosmo-1.1.dev516-py2.7-macosx-10.6-x86_64.egg/sncosmo/registry.pyc in retrieve(data_class, name, version)
    208         raise Exception(
    209             "No {0} named {1!r} in registry. Registered names: '{2}'"
--> 210             .format(data_class.__name__, name, "', '".join(registered_names)))
    211 
    212     registered_versions = [regkey[2] for regkey in _loaders.keys()

Exception: No TimeSeriesSource named 'nugent-sn1a' in registry. Registered names: ''

**Comment by kbarbary** [comment]
This is intentional. All the instances that are subclasses of `Source` are registered as `Source`. This is sort of an implementation detail; it just makes it easier to get a source by name.

Users are not really intended to use this function. Rather, `get_source()` and `get_bandpass()` should be used. As such, we might just want to consider removing `registry.retrieve` from the public documented API.
