### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by AlexGKim** [sncosmo/sncosmo#92]
I am reinstalling sncosmo after installing the lsst flavor of anaconda.  I get the following error.

tibia:sncosmo akim$ ./setup.py install
The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.  Attempting download instead.
Downloading astropy_helpers; run setup.py with the --offline option to force offline installation.
Traceback (most recent call last):
  File "./setup.py", line 66, in <module>
    cmdclassd = register_commands(PACKAGENAME, VERSION, RELEASE)
  File "/Users/akim/project/sncosmo/astropy_helpers-1.0.2-py2.7.egg/astropy_helpers/setup_helpers.py", line 295, in register_commands
    'build_ext': generate_build_ext_command(package, release),
  File "/Users/akim/project/sncosmo/astropy_helpers-1.0.2-py2.7.egg/astropy_helpers/commands/build_ext.py", line 63, in generate_build_ext_command
    uses_cython = should_build_with_cython(packagename, release)
  File "/Users/akim/project/sncosmo/astropy_helpers-1.0.2-py2.7.egg/astropy_helpers/commands/build_ext.py", line 23, in should_build_with_cython
    fromlist=['release', 'cython_version'])
  File "/Users/akim/project/sncosmo/sncosmo/__init__.py", line 20, in <module>
    from .version import version as __version__
  File "/Users/akim/project/sncosmo/sncosmo/version.py", line 191, in <module>
    version = update_git_devstr(_last_generated_version, path=__file__)
  File "/Users/akim/project/sncosmo/sncosmo/version.py", line 36, in update_git_devstr
    devstr = get_git_devstr(sha=True, show_warning=False, path=path)
  File "/Users/akim/project/sncosmo/sncosmo/version.py", line 129, in get_git_devstr
    returncode, stdout, stderr = run_git(cmd)
  File "/Users/akim/project/sncosmo/sncosmo/version.py", line 103, in run_git
    stdin=subprocess.PIPE)
  File "/Users/akim/local/lsst/DarwinX86/anaconda/2.1.0-4-g35ca374/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/akim/local/lsst/DarwinX86/anaconda/2.1.0-4-g35ca374/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

**Comment by kbarbary** [comment]
Looks like there's a problem when running  `git rev-parse HEAD` or `git rev-list --count HEAD`.
A couple things you could try, to help diagnose:

- Make sure these commands both work from the command line
- Install astropy-helpers from pip (`pip install astropy-helpers`) _I don't know why this would matter though_
- Try running git through subprocess and see what happens. For example:

```python
import subprocess

cmd = ['rev-list', '--count', 'HEAD']
subprocess.Popen(['git'] + cmd,
                 stdout=subprocess.PIPE,
                 stderr=subprocess.PIPE,
                 stdin=subprocess.PIPE)
```

**Comment by AlexGKim** [comment]
Both commands work from the command line.


I have installed astropy-helpers

I ran git through subprocess





In [2]: import subprocess




In [3]: cmd = ['rev-list', '--count', 'HEAD'] 




In [4]: subprocess.Popen(['git'] + cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, stdin=subprocess.PIPE)

Out[4]: <subprocess.Popen at 0x1038db690>




I still get the same error.




Note that I can install fine in my personal anaconda but not the one that the lsst stack pulled along with it.




Alex

**Comment by AlexGKim** [comment]
In case this is helpful to understand what is happening...




ipdb> builtin_mod.execfile(filename, *where)

*** UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

ipdb> print filename

/Users/akim/project/sncosmo/setup.py

ipdb> print where

({'LICENSE': 'BSD', 'URL': 'http://sncosmo.readthedocs.org', 'glob': <module 'glob' from '/Users/akim/local/lsst/DarwinX86/anaconda/2.1.0-4-g35ca374/lib/python2.7/glob.pyc'>, 'get_git_devstr': <function get_git_devstr at 0x104a968c0>, 'sys': <module 'sys' (built-in)>, 'adjust_compiler': <function adjust_compiler at 0x104b9f7d0>, 'AUTHOR_EMAIL': 'kylebarbary@gmail.com', 'recursive_glob': <function recursive_glob at 0x1052a0f50>, 'builtins': <module '__builtin__' (built-in)>, 'AUTHOR': 'The SNCosmo Developers', 'PACKAGENAME': 'sncosmo', '__package__': None, 'register_commands': <function register_commands at 0x104b9f500>, 'LONG_DESCRIPTION': '', '__builtins__': {'bytearray': <type 'bytearray'>, 'IndexError': <type 'exceptions.IndexError'>, 'all': <built-in function all>, 'help': Type help() for interactive help, or help(object) for help about object., 'vars': <built-in function vars>, 'SyntaxError': <type 'exceptions.SyntaxError'>, '__IPYTHON__active': 'Deprecated, check for __IPYTHON__', 'unicode': <type 'unicode'>, 'UnicodeDecodeError': <type 'exceptions.UnicodeDecodeError'>, 'memoryview': <type 'memoryview'>, 'isinstance': <built-in function isinstance>, 'copyright': Copyright (c) 2001-2014 Python Software Foundation.

All Rights Reserved.




Copyright (c) 2000 BeOpen.com.

All Rights Reserved.




Copyright (c) 1995-2001 Corporation for National Research Initiatives.

All Rights Reserved.




Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.

All Rights Reserved., 'NameError': <type 'exceptions.NameError'>, 'BytesWarning': <type 'exceptions.BytesWarning'>, 'dict': <type 'dict'>, '_ASTROPY_PACKAGE_NAME_': 'sncosmo', 'input': <built-in function input>, 'oct': <built-in function oct>, 'bin': <built-in function bin>, 'SystemExit': <type 'exceptions.SystemExit'>, 'StandardError': <type 'exceptions.StandardError'>, 'format': <built-in function format>, 'repr': <built-in function repr>, 'sorted': <built-in function sorted>, 'False': False, 'RuntimeWarning': <type 'exceptions.RuntimeWarning'>, 'list': <type 'list'>, 'iter': <built-in function iter>, 'reload': <built-in function reload>, 'Warning': <type 'exceptions.Warning'>, '__package__': None, 'round': <built-in function round>, 'dir': <built-in function dir>, 'cmp': <built-in function cmp>, 'set': <type 'set'>, 'bytes': <type 'str'>, 'reduce': <built-in function reduce>, 'intern': <built-in function intern>, 'issubclass': <built-in function issubclass>, 'Ellipsis': Ellipsis, 'EOFError': <type 'exceptions.EOFError'>, 'locals': <built-in function locals>, 'BufferError': <type 'exceptions.BufferError'>, 'slice': <type 'slice'>, 'FloatingPointError': <type 'exceptions.FloatingPointError'>, 'sum': <built-in function sum>, 'getattr': <built-in function getattr>, 'abs': <built-in function abs>, 'print': <built-in function print>, 'True': True, 'FutureWarning': <type 'exceptions.FutureWarning'>, 'ImportWarning': <type 'exceptions.ImportWarning'>, 'None': None, 'hash': <built-in function hash>, 'ReferenceError': <type 'exceptions.ReferenceError'>, 'len': <built-in function len>, 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands

    for supporting Python development.  See www.python.org for more information., 'frozenset': <type 'frozenset'>, '__name__': '__builtin__', 'ord': <built-in function ord>, 'super': <type 'super'>, 'TypeError': <type 'exceptions.TypeError'>, 'license': Type license() to see the full license text, 'KeyboardInterrupt': <type 'exceptions.KeyboardInterrupt'>, 'UserWarning': <type 'exceptions.UserWarning'>, 'filter': <built-in function filter>, 'range': <built-in function range>, 'staticmethod': <type 'staticmethod'>, 'SystemError': <type 'exceptions.SystemError'>, 'BaseException': <type 'exceptions.BaseException'>, 'pow': <built-in function pow>, 'RuntimeError': <type 'exceptions.RuntimeError'>, 'float': <type 'float'>, 'MemoryError': <type 'exceptions.MemoryError'>, 'StopIteration': <type 'exceptions.StopIteration'>, 'globals': <built-in function globals>, 'divmod': <built-in function divmod>, 'enumerate': <type 'enumerate'>, 'apply': <built-in function apply>, 'LookupError': <type 'exceptions.LookupError'>, 'open': <built-in function open>, 'basestring': <type 'basestring'>, 'UnicodeError': <type 'exceptions.UnicodeError'>, 'zip': <built-in function zip>, 'hex': <built-in function hex>, 'long': <type 'long'>, 'next': <built-in function next>, 'ImportError': <type 'exceptions.ImportError'>, 'chr': <built-in function chr>, 'xrange': <type 'xrange'>, 'type': <type 'type'>, '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", 'Exception': <type 'exceptions.Exception'>, '__IPYTHON__': True, 'tuple': <type 'tuple'>, 'UnicodeTranslateError': <type 'exceptions.UnicodeTranslateError'>, 'reversed': <type 'reversed'>, 'UnicodeEncodeError': <type 'exceptions.UnicodeEncodeError'>, 'IOError': <type 'exceptions.IOError'>, 'hasattr': <built-in function hasattr>, 'delattr': <built-in function delattr>, 'setattr': <built-in function setattr>, 'raw_input': <built-in function raw_input>, 'SyntaxWarning': <type 'exceptions.SyntaxWarning'>, 'compile': <built-in function compile>, 'ArithmeticError': <type 'exceptions.ArithmeticError'>, 'str': <type 'str'>, 'property': <type 'property'>, 'dreload': <function reload at 0x10330e6e0>, '_ASTROPY_SETUP_': True, 'GeneratorExit': <type 'exceptions.GeneratorExit'>, 'int': <type 'int'>, '__import__': <built-in function __import__>, 'KeyError': <type 'exceptions.KeyError'>, 'coerce': <built-in function coerce>, 'PendingDeprecationWarning': <type 'exceptions.PendingDeprecationWarning'>, 'file': <type 'file'>, 'EnvironmentError': <type 'exceptions.EnvironmentError'>, 'unichr': <built-in function unichr>, 'id': <built-in function id>, 'OSError': <type 'exceptions.OSError'>, 'DeprecationWarning': <type 'exceptions.DeprecationWarning'>, 'min': <built-in function min>, 'UnicodeWarning': <type 'exceptions.UnicodeWarning'>, 'execfile': <built-in function execfile>, 'any': <built-in function any>, 'complex': <type 'complex'>, 'bool': <type 'bool'>, 'get_ipython': <bound method TerminalInteractiveShell.get_ipython of <IPython.terminal.interactiveshell.TerminalInteractiveShell object at 0x1032dc990>>, 'ValueError': <type 'exceptions.ValueError'>, 'NotImplemented': NotImplemented, 'map': <built-in function map>, 'buffer': <type 'buffer'>, 'max': <built-in function max>, 'object': <type 'object'>, 'TabError': <type 'exceptions.TabError'>, 'callable': <built-in function callable>, 'ZeroDivisionError': <type 'exceptions.ZeroDivisionError'>, 'eval': <built-in function eval>, '__debug__': True, 'IndentationError': <type 'exceptions.IndentationError'>, 'AssertionError': <type 'exceptions.AssertionError'>, 'classmethod': <type 'classmethod'>, 'UnboundLocalError': <type 'exceptions.UnboundLocalError'>, 'NotImplementedError': <type 'exceptions.NotImplementedError'>, 'AttributeError': <type 'exceptions.AttributeError'>, 'OverflowError': <type 'exceptions.OverflowError'>}, 'get_package_info': <function get_package_info at 0x104b9f320>, '__file__': u'/Users/akim/project/sncosmo/setup.py', 'get_debug_option': <function get_debug_option at 0x104b9f578>, '__return__': None, '__exception__': (<type 'exceptions.UnicodeDecodeError'>, UnicodeDecodeError('ascii', '\xe2\x80\x9c/usr/local/bin', 0, 1, 'ordinal not in range(128)')), 'VERSION': u'1.1.dev516', 'astropy_helpers': <module 'astropy_helpers' from '/Users/akim/local/lsst/DarwinX86/anaconda/2.1.0-4-g35ca374/lib/python2.7/site-packages/astropy_helpers/__init__.pyc'>, 'RELEASE': False, '__name__': '__main__', 'generate_version_py': <function generate_version_py at 0x104a96b18>, '__nonzero__': <function <lambda> at 0x1051e6e60>, 'DESCRIPTION': 'Package for supernova cosmology based on astropy', 'setup': <function setup at 0x104a15de8>, 'fnmatch': <module 'fnmatch' from '/Users/akim/local/lsst/DarwinX86/anaconda/2.1.0-4-g35ca374/lib/python2.7/fnmatch.pyc'>, 'os': <module 'os' from '/Users/akim/local/lsst/DarwinX86/anaconda/2.1.0-4-g35ca374/lib/python2.7/os.pyc'>},)

**Comment by kbarbary** [comment]
Resolved as being unrelated to sncosmo.
