### ISSUE TITLE
Add Python 3 to Travis tests

### ISSUE THREAD

**Issue by kbarbary** [sncosmo/sncosmo#95]
This requires adding logic to `.travis.yml` to skip installing iminuit on Python 3 and marking tests that use iminuit as "skipif".

Maybe also enable appveyor while we're at it.

**Comment by eteq** [comment]
@kbarbary - for the second part, you might want to check out https://github.com/astropy/astropy/blob/master/astropy/utils/tests/test_decorators.py#L164 which is an example of who we do it in astropy (you can use `` from astropy.extern import six`` if you don't want to make six an explicit dependency).

**Comment by kbarbary** [comment]
Thanks, that looks good.
