### ISSUE TITLE
Add LSST bandpasses to built-ins

### ISSUE THREAD

**Issue by rbiswas4** [sncosmo/sncosmo#98]
I think it would be nice to add the LSST Bandpasses to the SNCosmo registry like we have the SDSS, DES bandpasses there etc. I can easily add them to the registry on my computer, but am wondering if we can put this in SNCosmo so that every user automatically gets it. 

The bandpasses are at:
https://github.com/lsst/throughputs and example files are 
https://github.com/lsst/throughputs/blob/master/baseline/total_g.dat

Any comments about sampling and extents  (Should we cut off the g filter at small enough values of transmission)?

**Comment by kbarbary** [comment]
Yes, I think it would be good to have these in sncosmo by default.

Given the way bandpass integration currently works in sncosmo, the LSST filters should be truncated and down-sampled to, say, a 5 Angstrom spacing. I'd really like to make this more automated in the future.

Think you can prepare a PR?

**Comment by rbiswas4** [comment]
> Given the way bandpass integration currently works in sncosmo, the LSST filters should be truncated and down-sampled to, say, a 5 Angstrom spacing. I'd really like to make this more automated in the future.

Agree. Should we have a prescription for truncation: T(\lambda) < epsilon for lambda outside this range? 
Or Energy for truncated range should be small? Or have the others been done by eyeballing the plot?

Finally, what do we need to do? 
- Add the truncated files to data with details of how and from where
- write a registry loader or can we use a common one providing arguments if the files are already in the same format? 
- And maybe this is a question for later (based on your comments), the LSST filters are in a github repository. Should we think of a way of doing the downloading and truncation through an automatic program? 
I will work on a PR for it.

**Comment by kbarbary** [comment]
Let's move discussion of better bandpass treatment to #99 and limit this issue to adding the LSST filters to the current system.

For the LSST filters, you should be able to follow the example from any other filter, specifically in `sncosmo/builtins.py` and `sncosmo/data/bandpasses/`.

**Comment by kbarbary** [comment]
Closed by 39161f266.
